using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementExternalExadataStorageConnectors
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementExternalExadataStorageConnectors.DataOciDatabaseManagementExternalExadataStorageConnectorsExternalExadataStorageConnectorCollection")]
    public class DataOciDatabaseManagementExternalExadataStorageConnectorsExternalExadataStorageConnectorCollection : oci.DataOciDatabaseManagementExternalExadataStorageConnectors.IDataOciDatabaseManagementExternalExadataStorageConnectorsExternalExadataStorageConnectorCollection
    {
    }
}
