using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciContainerInstancesContainerInstances
{
    [JsiiByValue(fqn: "oci.dataOciContainerInstancesContainerInstances.DataOciContainerInstancesContainerInstancesContainerInstanceCollectionItemsContainersHealthChecksHeaders")]
    public class DataOciContainerInstancesContainerInstancesContainerInstanceCollectionItemsContainersHealthChecksHeaders : oci.DataOciContainerInstancesContainerInstances.IDataOciContainerInstancesContainerInstancesContainerInstanceCollectionItemsContainersHealthChecksHeaders
    {
    }
}
