using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDataSafeSensitiveTypeGroupGroupedSensitiveTypes
{
    [JsiiByValue(fqn: "oci.dataOciDataSafeSensitiveTypeGroupGroupedSensitiveTypes.DataOciDataSafeSensitiveTypeGroupGroupedSensitiveTypesGroupedSensitiveTypeCollectionItemsItems")]
    public class DataOciDataSafeSensitiveTypeGroupGroupedSensitiveTypesGroupedSensitiveTypeCollectionItemsItems : oci.DataOciDataSafeSensitiveTypeGroupGroupedSensitiveTypes.IDataOciDataSafeSensitiveTypeGroupGroupedSensitiveTypesGroupedSensitiveTypeCollectionItemsItems
    {
    }
}
