using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseToolsRuntimeDatabaseToolsConnectionUserCredentials
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseToolsRuntimeDatabaseToolsConnectionUserCredentials.DataOciDatabaseToolsRuntimeDatabaseToolsConnectionUserCredentialsUserCredentialCollectionItemsRelatedResource")]
    public class DataOciDatabaseToolsRuntimeDatabaseToolsConnectionUserCredentialsUserCredentialCollectionItemsRelatedResource : oci.DataOciDatabaseToolsRuntimeDatabaseToolsConnectionUserCredentials.IDataOciDatabaseToolsRuntimeDatabaseToolsConnectionUserCredentialsUserCredentialCollectionItemsRelatedResource
    {
    }
}
