using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciTenantmanagercontrolplaneAssignedSubscriptionLineItems
{
    [JsiiByValue(fqn: "oci.dataOciTenantmanagercontrolplaneAssignedSubscriptionLineItems.DataOciTenantmanagercontrolplaneAssignedSubscriptionLineItemsAssignedSubscriptionLineItemCollection")]
    public class DataOciTenantmanagercontrolplaneAssignedSubscriptionLineItemsAssignedSubscriptionLineItemCollection : oci.DataOciTenantmanagercontrolplaneAssignedSubscriptionLineItems.IDataOciTenantmanagercontrolplaneAssignedSubscriptionLineItemsAssignedSubscriptionLineItemCollection
    {
    }
}
