using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciTenantmanagercontrolplaneAssignedSubscriptionLineItems
{
    [JsiiByValue(fqn: "oci.dataOciTenantmanagercontrolplaneAssignedSubscriptionLineItems.DataOciTenantmanagercontrolplaneAssignedSubscriptionLineItemsAssignedSubscriptionLineItemCollectionItems")]
    public class DataOciTenantmanagercontrolplaneAssignedSubscriptionLineItemsAssignedSubscriptionLineItemCollectionItems : oci.DataOciTenantmanagercontrolplaneAssignedSubscriptionLineItems.IDataOciTenantmanagercontrolplaneAssignedSubscriptionLineItemsAssignedSubscriptionLineItemCollectionItems
    {
    }
}
