using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciResourceAnalyticsResourceAnalyticsInstances
{
    [JsiiByValue(fqn: "oci.dataOciResourceAnalyticsResourceAnalyticsInstances.DataOciResourceAnalyticsResourceAnalyticsInstancesResourceAnalyticsInstanceCollectionItemsAdwAdminPassword")]
    public class DataOciResourceAnalyticsResourceAnalyticsInstancesResourceAnalyticsInstanceCollectionItemsAdwAdminPassword : oci.DataOciResourceAnalyticsResourceAnalyticsInstances.IDataOciResourceAnalyticsResourceAnalyticsInstancesResourceAnalyticsInstanceCollectionItemsAdwAdminPassword
    {
    }
}
