using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDistributedDatabaseDistributedDatabasePrivateEndpoints
{
    [JsiiByValue(fqn: "oci.dataOciDistributedDatabaseDistributedDatabasePrivateEndpoints.DataOciDistributedDatabaseDistributedDatabasePrivateEndpointsDistributedDatabasePrivateEndpointCollectionItemsGloballyDistributedDatabases")]
    public class DataOciDistributedDatabaseDistributedDatabasePrivateEndpointsDistributedDatabasePrivateEndpointCollectionItemsGloballyDistributedDatabases : oci.DataOciDistributedDatabaseDistributedDatabasePrivateEndpoints.IDataOciDistributedDatabaseDistributedDatabasePrivateEndpointsDistributedDatabasePrivateEndpointCollectionItemsGloballyDistributedDatabases
    {
    }
}
