using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciNetworkFirewallNetworkFirewallPolicyDecryptionRules
{
    [JsiiByValue(fqn: "oci.dataOciNetworkFirewallNetworkFirewallPolicyDecryptionRules.DataOciNetworkFirewallNetworkFirewallPolicyDecryptionRulesDecryptionRuleSummaryCollectionItemsCondition")]
    public class DataOciNetworkFirewallNetworkFirewallPolicyDecryptionRulesDecryptionRuleSummaryCollectionItemsCondition : oci.DataOciNetworkFirewallNetworkFirewallPolicyDecryptionRules.IDataOciNetworkFirewallNetworkFirewallPolicyDecryptionRulesDecryptionRuleSummaryCollectionItemsCondition
    {
    }
}
