using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciOsManagementHubSoftwareSourceSoftwarePackages
{
    [JsiiByValue(fqn: "oci.dataOciOsManagementHubSoftwareSourceSoftwarePackages.DataOciOsManagementHubSoftwareSourceSoftwarePackagesSoftwarePackageCollectionItemsDependencies")]
    public class DataOciOsManagementHubSoftwareSourceSoftwarePackagesSoftwarePackageCollectionItemsDependencies : oci.DataOciOsManagementHubSoftwareSourceSoftwarePackages.IDataOciOsManagementHubSoftwareSourceSoftwarePackagesSoftwarePackageCollectionItemsDependencies
    {
    }
}
