using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace stripe.Subscription
{
    [JsiiInterface(nativeType: typeof(ISubscriptionInvoiceSettings), fullyQualifiedName: "stripe.subscription.SubscriptionInvoiceSettings")]
    public interface ISubscriptionInvoiceSettings
    {
        /// <summary>The account tax IDs associated with the subscription. Will be set on invoices generated by the subscription.</summary>
        /// <remarks>
        /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stripe/stripe/0.3.0/docs/resources/subscription#account_tax_ids Subscription#account_tax_ids}
        /// </remarks>
        [JsiiProperty(name: "accountTaxIds", typeJson: "{\"collection\":{\"elementtype\":{\"primitive\":\"string\"},\"kind\":\"array\"}}", isOptional: true)]
        [Amazon.JSII.Runtime.Deputy.JsiiOptional]
        string[]? AccountTaxIds
        {
            get
            {
                return null;
            }
        }

        /// <summary>Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stripe/stripe/0.3.0/docs/resources/subscription#issuer Subscription#issuer}.</summary>
        [JsiiProperty(name: "issuer", typeJson: "{\"fqn\":\"stripe.subscription.SubscriptionInvoiceSettingsIssuer\"}", isOptional: true)]
        [Amazon.JSII.Runtime.Deputy.JsiiOptional]
        stripe.Subscription.ISubscriptionInvoiceSettingsIssuer? Issuer
        {
            get
            {
                return null;
            }
        }

        [JsiiTypeProxy(nativeType: typeof(ISubscriptionInvoiceSettings), fullyQualifiedName: "stripe.subscription.SubscriptionInvoiceSettings")]
        internal sealed class _Proxy : DeputyBase, stripe.Subscription.ISubscriptionInvoiceSettings
        {
            private _Proxy(ByRefValue reference): base(reference)
            {
            }

            /// <summary>The account tax IDs associated with the subscription. Will be set on invoices generated by the subscription.</summary>
            /// <remarks>
            /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stripe/stripe/0.3.0/docs/resources/subscription#account_tax_ids Subscription#account_tax_ids}
            /// </remarks>
            [JsiiOptional]
            [JsiiProperty(name: "accountTaxIds", typeJson: "{\"collection\":{\"elementtype\":{\"primitive\":\"string\"},\"kind\":\"array\"}}", isOptional: true)]
            public string[]? AccountTaxIds
            {
                get => GetInstanceProperty<string[]?>();
            }

            /// <summary>Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stripe/stripe/0.3.0/docs/resources/subscription#issuer Subscription#issuer}.</summary>
            [JsiiOptional]
            [JsiiProperty(name: "issuer", typeJson: "{\"fqn\":\"stripe.subscription.SubscriptionInvoiceSettingsIssuer\"}", isOptional: true)]
            public stripe.Subscription.ISubscriptionInvoiceSettingsIssuer? Issuer
            {
                get => GetInstanceProperty<stripe.Subscription.ISubscriptionInvoiceSettingsIssuer?>();
            }
        }
    }
}
