using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciIdentityDomainsUserDbCredentials
{
    [JsiiByValue(fqn: "oci.dataOciIdentityDomainsUserDbCredentials.DataOciIdentityDomainsUserDbCredentialsUserDbCredentialsUrnietfparamsscimschemasoracleidcsextensionselfChangeUser")]
    public class DataOciIdentityDomainsUserDbCredentialsUserDbCredentialsUrnietfparamsscimschemasoracleidcsextensionselfChangeUser : oci.DataOciIdentityDomainsUserDbCredentials.IDataOciIdentityDomainsUserDbCredentialsUserDbCredentialsUrnietfparamsscimschemasoracleidcsextensionselfChangeUser
    {
    }
}
