using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementManagedMySqlDatabaseDigestErrors
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementManagedMySqlDatabaseDigestErrors.DataOciDatabaseManagementManagedMySqlDatabaseDigestErrorsMySqlDigestErrorsCollectionItems")]
    public class DataOciDatabaseManagementManagedMySqlDatabaseDigestErrorsMySqlDigestErrorsCollectionItems : oci.DataOciDatabaseManagementManagedMySqlDatabaseDigestErrors.IDataOciDatabaseManagementManagedMySqlDatabaseDigestErrorsMySqlDigestErrorsCollectionItems
    {
    }
}
