using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDataintegrationWorkspaceApplicationSchedule
{
    [JsiiByValue(fqn: "oci.dataOciDataintegrationWorkspaceApplicationSchedule.DataOciDataintegrationWorkspaceApplicationScheduleMetadataCountStatisticsObjectTypeCountListStruct")]
    public class DataOciDataintegrationWorkspaceApplicationScheduleMetadataCountStatisticsObjectTypeCountListStruct : oci.DataOciDataintegrationWorkspaceApplicationSchedule.IDataOciDataintegrationWorkspaceApplicationScheduleMetadataCountStatisticsObjectTypeCountListStruct
    {
    }
}
