using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseToolsDatabaseToolsDatabaseApiGatewayConfigs
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseToolsDatabaseToolsDatabaseApiGatewayConfigs.DataOciDatabaseToolsDatabaseToolsDatabaseApiGatewayConfigsDatabaseToolsDatabaseApiGatewayConfigCollection")]
    public class DataOciDatabaseToolsDatabaseToolsDatabaseApiGatewayConfigsDatabaseToolsDatabaseApiGatewayConfigCollection : oci.DataOciDatabaseToolsDatabaseToolsDatabaseApiGatewayConfigs.IDataOciDatabaseToolsDatabaseToolsDatabaseApiGatewayConfigsDatabaseToolsDatabaseApiGatewayConfigCollection
    {
    }
}
