using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciTenantmanagercontrolplaneAssignedSubscriptions
{
    [JsiiByValue(fqn: "oci.dataOciTenantmanagercontrolplaneAssignedSubscriptions.DataOciTenantmanagercontrolplaneAssignedSubscriptionsAssignedSubscriptionCollectionItemsPromotion")]
    public class DataOciTenantmanagercontrolplaneAssignedSubscriptionsAssignedSubscriptionCollectionItemsPromotion : oci.DataOciTenantmanagercontrolplaneAssignedSubscriptions.IDataOciTenantmanagercontrolplaneAssignedSubscriptionsAssignedSubscriptionCollectionItemsPromotion
    {
    }
}
