using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciOsManagementHubManagedInstanceAvailablePackages
{
    [JsiiByValue(fqn: "oci.dataOciOsManagementHubManagedInstanceAvailablePackages.DataOciOsManagementHubManagedInstanceAvailablePackagesAvailablePackageCollectionItemsSoftwareSources")]
    public class DataOciOsManagementHubManagedInstanceAvailablePackagesAvailablePackageCollectionItemsSoftwareSources : oci.DataOciOsManagementHubManagedInstanceAvailablePackages.IDataOciOsManagementHubManagedInstanceAvailablePackagesAvailablePackageCollectionItemsSoftwareSources
    {
    }
}
