using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciCapacityManagementInternalOccmDemandSignalDeliveries
{
    [JsiiByValue(fqn: "oci.dataOciCapacityManagementInternalOccmDemandSignalDeliveries.DataOciCapacityManagementInternalOccmDemandSignalDeliveriesInternalOccmDemandSignalDeliveryCollectionItems")]
    public class DataOciCapacityManagementInternalOccmDemandSignalDeliveriesInternalOccmDemandSignalDeliveryCollectionItems : oci.DataOciCapacityManagementInternalOccmDemandSignalDeliveries.IDataOciCapacityManagementInternalOccmDemandSignalDeliveriesInternalOccmDemandSignalDeliveryCollectionItems
    {
    }
}
