using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciApigatewayDeployments
{
    [JsiiByValue(fqn: "oci.dataOciApigatewayDeployments.DataOciApigatewayDeploymentsDeploymentCollectionSpecificationRoutesRequestPoliciesQueryParameterTransformationsRenameQueryParametersItems")]
    public class DataOciApigatewayDeploymentsDeploymentCollectionSpecificationRoutesRequestPoliciesQueryParameterTransformationsRenameQueryParametersItems : oci.DataOciApigatewayDeployments.IDataOciApigatewayDeploymentsDeploymentCollectionSpecificationRoutesRequestPoliciesQueryParameterTransformationsRenameQueryParametersItems
    {
    }
}
