using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciApigatewayDeployments
{
    [JsiiByValue(fqn: "oci.dataOciApigatewayDeployments.DataOciApigatewayDeploymentsDeploymentCollectionSpecificationRoutesRequestPoliciesHeaderTransformationsFilterHeadersItems")]
    public class DataOciApigatewayDeploymentsDeploymentCollectionSpecificationRoutesRequestPoliciesHeaderTransformationsFilterHeadersItems : oci.DataOciApigatewayDeployments.IDataOciApigatewayDeploymentsDeploymentCollectionSpecificationRoutesRequestPoliciesHeaderTransformationsFilterHeadersItems
    {
    }
}
