using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDataSafeSensitiveDataModelReferentialRelations
{
    [JsiiByValue(fqn: "oci.dataOciDataSafeSensitiveDataModelReferentialRelations.DataOciDataSafeSensitiveDataModelReferentialRelationsReferentialRelationCollectionItemsParent")]
    public class DataOciDataSafeSensitiveDataModelReferentialRelationsReferentialRelationCollectionItemsParent : oci.DataOciDataSafeSensitiveDataModelReferentialRelations.IDataOciDataSafeSensitiveDataModelReferentialRelationsReferentialRelationCollectionItemsParent
    {
    }
}
