using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciApiaccesscontrolPrivilegedApiControls
{
    [JsiiByValue(fqn: "oci.dataOciApiaccesscontrolPrivilegedApiControls.DataOciApiaccesscontrolPrivilegedApiControlsPrivilegedApiControlCollectionItemsPrivilegedOperationListStruct")]
    public class DataOciApiaccesscontrolPrivilegedApiControlsPrivilegedApiControlCollectionItemsPrivilegedOperationListStruct : oci.DataOciApiaccesscontrolPrivilegedApiControls.IDataOciApiaccesscontrolPrivilegedApiControlsPrivilegedApiControlCollectionItemsPrivilegedOperationListStruct
    {
    }
}
