using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciCapacityManagementInternalOccmDemandSignalItems
{
    [JsiiByValue(fqn: "oci.dataOciCapacityManagementInternalOccmDemandSignalItems.DataOciCapacityManagementInternalOccmDemandSignalItemsInternalOccmDemandSignalItemCollection")]
    public class DataOciCapacityManagementInternalOccmDemandSignalItemsInternalOccmDemandSignalItemCollection : oci.DataOciCapacityManagementInternalOccmDemandSignalItems.IDataOciCapacityManagementInternalOccmDemandSignalItemsInternalOccmDemandSignalItemCollection
    {
    }
}
