using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciLustreFileStorageAvailableMaintenanceScheduleStartTimes
{
    [JsiiByValue(fqn: "oci.dataOciLustreFileStorageAvailableMaintenanceScheduleStartTimes.DataOciLustreFileStorageAvailableMaintenanceScheduleStartTimesAvailableMaintenanceScheduleStartTimeCollection")]
    public class DataOciLustreFileStorageAvailableMaintenanceScheduleStartTimesAvailableMaintenanceScheduleStartTimeCollection : oci.DataOciLustreFileStorageAvailableMaintenanceScheduleStartTimes.IDataOciLustreFileStorageAvailableMaintenanceScheduleStartTimesAvailableMaintenanceScheduleStartTimeCollection
    {
    }
}
