using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciStackMonitoringDefinedMonitoringTemplates
{
    [JsiiByValue(fqn: "oci.dataOciStackMonitoringDefinedMonitoringTemplates.DataOciStackMonitoringDefinedMonitoringTemplatesDefinedMonitoringTemplateCollectionItemsDefinedAlarmConditionsConditions")]
    public class DataOciStackMonitoringDefinedMonitoringTemplatesDefinedMonitoringTemplateCollectionItemsDefinedAlarmConditionsConditions : oci.DataOciStackMonitoringDefinedMonitoringTemplates.IDataOciStackMonitoringDefinedMonitoringTemplatesDefinedMonitoringTemplateCollectionItemsDefinedAlarmConditionsConditions
    {
    }
}
