using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciStackMonitoringDefinedMonitoringTemplates
{
    [JsiiByValue(fqn: "oci.dataOciStackMonitoringDefinedMonitoringTemplates.DataOciStackMonitoringDefinedMonitoringTemplatesDefinedMonitoringTemplateCollectionItemsDefinedAlarmConditions")]
    public class DataOciStackMonitoringDefinedMonitoringTemplatesDefinedMonitoringTemplateCollectionItemsDefinedAlarmConditions : oci.DataOciStackMonitoringDefinedMonitoringTemplates.IDataOciStackMonitoringDefinedMonitoringTemplatesDefinedMonitoringTemplateCollectionItemsDefinedAlarmConditions
    {
    }
}
