using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseAutonomousContainerDatabaseBackups
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseAutonomousContainerDatabaseBackups.DataOciDatabaseAutonomousContainerDatabaseBackupsAutonomousContainerDatabaseBackupCollectionItemsAutonomousDatabases")]
    public class DataOciDatabaseAutonomousContainerDatabaseBackupsAutonomousContainerDatabaseBackupCollectionItemsAutonomousDatabases : oci.DataOciDatabaseAutonomousContainerDatabaseBackups.IDataOciDatabaseAutonomousContainerDatabaseBackupsAutonomousContainerDatabaseBackupCollectionItemsAutonomousDatabases
    {
    }
}
