using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementExternalExadataInfrastructures
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementExternalExadataInfrastructures.DataOciDatabaseManagementExternalExadataInfrastructuresExternalExadataInfrastructureCollection")]
    public class DataOciDatabaseManagementExternalExadataInfrastructuresExternalExadataInfrastructureCollection : oci.DataOciDatabaseManagementExternalExadataInfrastructures.IDataOciDatabaseManagementExternalExadataInfrastructuresExternalExadataInfrastructureCollection
    {
    }
}
