using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementExternalExadataInfrastructures
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementExternalExadataInfrastructures.DataOciDatabaseManagementExternalExadataInfrastructuresExternalExadataInfrastructureCollectionItems")]
    public class DataOciDatabaseManagementExternalExadataInfrastructuresExternalExadataInfrastructureCollectionItems : oci.DataOciDatabaseManagementExternalExadataInfrastructures.IDataOciDatabaseManagementExternalExadataInfrastructuresExternalExadataInfrastructureCollectionItems
    {
    }
}
