using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonyms
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonyms.DataOciDatabaseToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymsCredentialPublicSynonymCollection")]
    public class DataOciDatabaseToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymsCredentialPublicSynonymCollection : oci.DataOciDatabaseToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonyms.IDataOciDatabaseToolsRuntimeDatabaseToolsConnectionCredentialPublicSynonymsCredentialPublicSynonymCollection
    {
    }
}
