using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementDbManagementPrivateEndpointAssociatedDatabases
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementDbManagementPrivateEndpointAssociatedDatabases.DataOciDatabaseManagementDbManagementPrivateEndpointAssociatedDatabasesAssociatedDatabaseCollection")]
    public class DataOciDatabaseManagementDbManagementPrivateEndpointAssociatedDatabasesAssociatedDatabaseCollection : oci.DataOciDatabaseManagementDbManagementPrivateEndpointAssociatedDatabases.IDataOciDatabaseManagementDbManagementPrivateEndpointAssociatedDatabasesAssociatedDatabaseCollection
    {
    }
}
