using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciCapacityManagementOccAvailabilityCatalogOccAvailabilities
{
    [JsiiByValue(fqn: "oci.dataOciCapacityManagementOccAvailabilityCatalogOccAvailabilities.DataOciCapacityManagementOccAvailabilityCatalogOccAvailabilitiesOccAvailabilityCollection")]
    public class DataOciCapacityManagementOccAvailabilityCatalogOccAvailabilitiesOccAvailabilityCollection : oci.DataOciCapacityManagementOccAvailabilityCatalogOccAvailabilities.IDataOciCapacityManagementOccAvailabilityCatalogOccAvailabilitiesOccAvailabilityCollection
    {
    }
}
