using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDistributedDatabaseDistributedDatabasePrivateEndpoint
{
    [JsiiByValue(fqn: "oci.dataOciDistributedDatabaseDistributedDatabasePrivateEndpoint.DataOciDistributedDatabaseDistributedDatabasePrivateEndpointGloballyDistributedAutonomousDatabases")]
    public class DataOciDistributedDatabaseDistributedDatabasePrivateEndpointGloballyDistributedAutonomousDatabases : oci.DataOciDistributedDatabaseDistributedDatabasePrivateEndpoint.IDataOciDistributedDatabaseDistributedDatabasePrivateEndpointGloballyDistributedAutonomousDatabases
    {
    }
}
