using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementExternalExadataStorageServerTopSqlCpuActivity
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementExternalExadataStorageServerTopSqlCpuActivity.DataOciDatabaseManagementExternalExadataStorageServerTopSqlCpuActivityActivity")]
    public class DataOciDatabaseManagementExternalExadataStorageServerTopSqlCpuActivityActivity : oci.DataOciDatabaseManagementExternalExadataStorageServerTopSqlCpuActivity.IDataOciDatabaseManagementExternalExadataStorageServerTopSqlCpuActivityActivity
    {
    }
}
