using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDataSafeRegistrationPolicyTargetDatabases
{
    [JsiiByValue(fqn: "oci.dataOciDataSafeRegistrationPolicyTargetDatabases.DataOciDataSafeRegistrationPolicyTargetDatabasesRegistrationPolicyTargetDatabaseSummaryCollectionItems")]
    public class DataOciDataSafeRegistrationPolicyTargetDatabasesRegistrationPolicyTargetDatabaseSummaryCollectionItems : oci.DataOciDataSafeRegistrationPolicyTargetDatabases.IDataOciDataSafeRegistrationPolicyTargetDatabasesRegistrationPolicyTargetDatabaseSummaryCollectionItems
    {
    }
}
