using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciOsManagementHubManagedInstanceAvailableWindowsUpdates
{
    [JsiiByValue(fqn: "oci.dataOciOsManagementHubManagedInstanceAvailableWindowsUpdates.DataOciOsManagementHubManagedInstanceAvailableWindowsUpdatesAvailableWindowsUpdateCollection")]
    public class DataOciOsManagementHubManagedInstanceAvailableWindowsUpdatesAvailableWindowsUpdateCollection : oci.DataOciOsManagementHubManagedInstanceAvailableWindowsUpdates.IDataOciOsManagementHubManagedInstanceAvailableWindowsUpdatesAvailableWindowsUpdateCollection
    {
    }
}
