using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementManagedDatabaseSqlTuningAdvisorTasksRecommendation
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementManagedDatabaseSqlTuningAdvisorTasksRecommendation.DataOciDatabaseManagementManagedDatabaseSqlTuningAdvisorTasksRecommendationItems")]
    public class DataOciDatabaseManagementManagedDatabaseSqlTuningAdvisorTasksRecommendationItems : oci.DataOciDatabaseManagementManagedDatabaseSqlTuningAdvisorTasksRecommendation.IDataOciDatabaseManagementManagedDatabaseSqlTuningAdvisorTasksRecommendationItems
    {
    }
}
