using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatascienceMlApplicationImplementationVersions
{
    [JsiiByValue(fqn: "oci.dataOciDatascienceMlApplicationImplementationVersions.DataOciDatascienceMlApplicationImplementationVersionsMlApplicationImplementationVersionCollectionItemsConfigurationSchema")]
    public class DataOciDatascienceMlApplicationImplementationVersionsMlApplicationImplementationVersionCollectionItemsConfigurationSchema : oci.DataOciDatascienceMlApplicationImplementationVersions.IDataOciDatascienceMlApplicationImplementationVersionsMlApplicationImplementationVersionCollectionItemsConfigurationSchema
    {
    }
}
