using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatascienceMlApplicationImplementationVersions
{
    [JsiiByValue(fqn: "oci.dataOciDatascienceMlApplicationImplementationVersions.DataOciDatascienceMlApplicationImplementationVersionsMlApplicationImplementationVersionCollectionItemsMlApplicationPackageArguments")]
    public class DataOciDatascienceMlApplicationImplementationVersionsMlApplicationImplementationVersionCollectionItemsMlApplicationPackageArguments : oci.DataOciDatascienceMlApplicationImplementationVersions.IDataOciDatascienceMlApplicationImplementationVersionsMlApplicationImplementationVersionCollectionItemsMlApplicationPackageArguments
    {
    }
}
