using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciLustreFileStorageAvailableOverrideMaintenanceStartTimes
{
    [JsiiByValue(fqn: "oci.dataOciLustreFileStorageAvailableOverrideMaintenanceStartTimes.DataOciLustreFileStorageAvailableOverrideMaintenanceStartTimesAvailableOverrideMaintenanceStartTimeCollectionItems")]
    public class DataOciLustreFileStorageAvailableOverrideMaintenanceStartTimesAvailableOverrideMaintenanceStartTimeCollectionItems : oci.DataOciLustreFileStorageAvailableOverrideMaintenanceStartTimes.IDataOciLustreFileStorageAvailableOverrideMaintenanceStartTimesAvailableOverrideMaintenanceStartTimeCollectionItems
    {
    }
}
