using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciMeteringComputationUsageCarbonEmissionsQueries
{
    [JsiiByValue(fqn: "oci.dataOciMeteringComputationUsageCarbonEmissionsQueries.DataOciMeteringComputationUsageCarbonEmissionsQueriesUsageCarbonEmissionsQueryCollectionItemsQueryDefinitionReportQueryGroupByTag")]
    public class DataOciMeteringComputationUsageCarbonEmissionsQueriesUsageCarbonEmissionsQueryCollectionItemsQueryDefinitionReportQueryGroupByTag : oci.DataOciMeteringComputationUsageCarbonEmissionsQueries.IDataOciMeteringComputationUsageCarbonEmissionsQueriesUsageCarbonEmissionsQueryCollectionItemsQueryDefinitionReportQueryGroupByTag
    {
    }
}
