using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementManagedMySqlDatabaseConfigurationData
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementManagedMySqlDatabaseConfigurationData.DataOciDatabaseManagementManagedMySqlDatabaseConfigurationDataMySqlConfigurationDataCollection")]
    public class DataOciDatabaseManagementManagedMySqlDatabaseConfigurationDataMySqlConfigurationDataCollection : oci.DataOciDatabaseManagementManagedMySqlDatabaseConfigurationData.IDataOciDatabaseManagementManagedMySqlDatabaseConfigurationDataMySqlConfigurationDataCollection
    {
    }
}
