using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatascienceJobRuns
{
    [JsiiByValue(fqn: "oci.dataOciDatascienceJobRuns.DataOciDatascienceJobRunsJobRunsJobInfrastructureConfigurationOverrideDetailsResourceConfigurationResourceRequestConfiguration")]
    public class DataOciDatascienceJobRunsJobRunsJobInfrastructureConfigurationOverrideDetailsResourceConfigurationResourceRequestConfiguration : oci.DataOciDatascienceJobRuns.IDataOciDatascienceJobRunsJobRunsJobInfrastructureConfigurationOverrideDetailsResourceConfigurationResourceRequestConfiguration
    {
    }
}
