using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace stripe.SubscriptionSchedule
{
    [JsiiInterface(nativeType: typeof(ISubscriptionSchedulePhasesInvoiceSettings), fullyQualifiedName: "stripe.subscriptionSchedule.SubscriptionSchedulePhasesInvoiceSettings")]
    public interface ISubscriptionSchedulePhasesInvoiceSettings
    {
        /// <summary>The account tax IDs associated with this phase of the subscription schedule.</summary>
        /// <remarks>
        /// Will be set on invoices generated by this phase of the subscription schedule.
        ///
        /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stripe/stripe/0.3.0/docs/resources/subscription_schedule#account_tax_ids SubscriptionSchedule#account_tax_ids}
        /// </remarks>
        [JsiiProperty(name: "accountTaxIds", typeJson: "{\"collection\":{\"elementtype\":{\"primitive\":\"string\"},\"kind\":\"array\"}}", isOptional: true)]
        [Amazon.JSII.Runtime.Deputy.JsiiOptional]
        string[]? AccountTaxIds
        {
            get
            {
                return null;
            }
        }

        /// <summary>Number of days within which a customer must pay invoices generated by this subscription schedule.</summary>
        /// <remarks>
        /// This value will be <c>null</c> for subscription schedules where <c>billing=charge_automatically</c>.
        ///
        /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stripe/stripe/0.3.0/docs/resources/subscription_schedule#days_until_due SubscriptionSchedule#days_until_due}
        /// </remarks>
        [JsiiProperty(name: "daysUntilDue", typeJson: "{\"primitive\":\"number\"}", isOptional: true)]
        [Amazon.JSII.Runtime.Deputy.JsiiOptional]
        double? DaysUntilDue
        {
            get
            {
                return null;
            }
        }

        /// <summary>The connected account that issues the invoice.</summary>
        /// <remarks>
        /// The invoice is presented with the branding and support information of the specified account.
        ///
        /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stripe/stripe/0.3.0/docs/resources/subscription_schedule#issuer SubscriptionSchedule#issuer}
        /// </remarks>
        [JsiiProperty(name: "issuer", typeJson: "{\"fqn\":\"stripe.subscriptionSchedule.SubscriptionSchedulePhasesInvoiceSettingsIssuer\"}", isOptional: true)]
        [Amazon.JSII.Runtime.Deputy.JsiiOptional]
        stripe.SubscriptionSchedule.ISubscriptionSchedulePhasesInvoiceSettingsIssuer? Issuer
        {
            get
            {
                return null;
            }
        }

        [JsiiTypeProxy(nativeType: typeof(ISubscriptionSchedulePhasesInvoiceSettings), fullyQualifiedName: "stripe.subscriptionSchedule.SubscriptionSchedulePhasesInvoiceSettings")]
        internal sealed class _Proxy : DeputyBase, stripe.SubscriptionSchedule.ISubscriptionSchedulePhasesInvoiceSettings
        {
            private _Proxy(ByRefValue reference): base(reference)
            {
            }

            /// <summary>The account tax IDs associated with this phase of the subscription schedule.</summary>
            /// <remarks>
            /// Will be set on invoices generated by this phase of the subscription schedule.
            ///
            /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stripe/stripe/0.3.0/docs/resources/subscription_schedule#account_tax_ids SubscriptionSchedule#account_tax_ids}
            /// </remarks>
            [JsiiOptional]
            [JsiiProperty(name: "accountTaxIds", typeJson: "{\"collection\":{\"elementtype\":{\"primitive\":\"string\"},\"kind\":\"array\"}}", isOptional: true)]
            public string[]? AccountTaxIds
            {
                get => GetInstanceProperty<string[]?>();
            }

            /// <summary>Number of days within which a customer must pay invoices generated by this subscription schedule.</summary>
            /// <remarks>
            /// This value will be <c>null</c> for subscription schedules where <c>billing=charge_automatically</c>.
            ///
            /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stripe/stripe/0.3.0/docs/resources/subscription_schedule#days_until_due SubscriptionSchedule#days_until_due}
            /// </remarks>
            [JsiiOptional]
            [JsiiProperty(name: "daysUntilDue", typeJson: "{\"primitive\":\"number\"}", isOptional: true)]
            public double? DaysUntilDue
            {
                get => GetInstanceProperty<double?>();
            }

            /// <summary>The connected account that issues the invoice.</summary>
            /// <remarks>
            /// The invoice is presented with the branding and support information of the specified account.
            ///
            /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stripe/stripe/0.3.0/docs/resources/subscription_schedule#issuer SubscriptionSchedule#issuer}
            /// </remarks>
            [JsiiOptional]
            [JsiiProperty(name: "issuer", typeJson: "{\"fqn\":\"stripe.subscriptionSchedule.SubscriptionSchedulePhasesInvoiceSettingsIssuer\"}", isOptional: true)]
            public stripe.SubscriptionSchedule.ISubscriptionSchedulePhasesInvoiceSettingsIssuer? Issuer
            {
                get => GetInstanceProperty<stripe.SubscriptionSchedule.ISubscriptionSchedulePhasesInvoiceSettingsIssuer?>();
            }
        }
    }
}
