using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace stripe.SubscriptionSchedule
{
    [JsiiByValue(fqn: "stripe.subscriptionSchedule.SubscriptionScheduleDefaultSettingsInvoiceSettings")]
    public class SubscriptionScheduleDefaultSettingsInvoiceSettings : stripe.SubscriptionSchedule.ISubscriptionScheduleDefaultSettingsInvoiceSettings
    {
        /// <summary>The account tax IDs associated with the subscription schedule. Will be set on invoices generated by the subscription schedule.</summary>
        /// <remarks>
        /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stripe/stripe/0.3.0/docs/resources/subscription_schedule#account_tax_ids SubscriptionSchedule#account_tax_ids}
        /// </remarks>
        [JsiiOptional]
        [JsiiProperty(name: "accountTaxIds", typeJson: "{\"collection\":{\"elementtype\":{\"primitive\":\"string\"},\"kind\":\"array\"}}", isOptional: true)]
        public string[]? AccountTaxIds
        {
            get;
            set;
        }

        /// <summary>Number of days within which a customer must pay invoices generated by this subscription schedule.</summary>
        /// <remarks>
        /// This value will be <c>null</c> for subscription schedules where <c>billing=charge_automatically</c>.
        ///
        /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stripe/stripe/0.3.0/docs/resources/subscription_schedule#days_until_due SubscriptionSchedule#days_until_due}
        /// </remarks>
        [JsiiOptional]
        [JsiiProperty(name: "daysUntilDue", typeJson: "{\"primitive\":\"number\"}", isOptional: true)]
        public double? DaysUntilDue
        {
            get;
            set;
        }

        /// <summary>Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stripe/stripe/0.3.0/docs/resources/subscription_schedule#issuer SubscriptionSchedule#issuer}.</summary>
        [JsiiOptional]
        [JsiiProperty(name: "issuer", typeJson: "{\"fqn\":\"stripe.subscriptionSchedule.SubscriptionScheduleDefaultSettingsInvoiceSettingsIssuer\"}", isOptional: true)]
        public stripe.SubscriptionSchedule.ISubscriptionScheduleDefaultSettingsInvoiceSettingsIssuer? Issuer
        {
            get;
            set;
        }
    }
}
