using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatascienceJobs
{
    [JsiiByValue(fqn: "oci.dataOciDatascienceJobs.DataOciDatascienceJobsJobsJobNodeConfigurationDetailsJobNodeGroupConfigurationDetailsListJobConfigurationDetailsStartupProbeDetails")]
    public class DataOciDatascienceJobsJobsJobNodeConfigurationDetailsJobNodeGroupConfigurationDetailsListJobConfigurationDetailsStartupProbeDetails : oci.DataOciDatascienceJobs.IDataOciDatascienceJobsJobsJobNodeConfigurationDetailsJobNodeGroupConfigurationDetailsListJobConfigurationDetailsStartupProbeDetails
    {
    }
}
