using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace stripe.SetupIntent
{
    [JsiiInterface(nativeType: typeof(ISetupIntentPaymentMethodOptionsPaypal), fullyQualifiedName: "stripe.setupIntent.SetupIntentPaymentMethodOptionsPaypal")]
    public interface ISetupIntentPaymentMethodOptionsPaypal
    {
        /// <summary>The PayPal Billing Agreement ID (BAID).</summary>
        /// <remarks>
        /// This is an ID generated by PayPal which represents the mandate between the merchant and the customer.
        ///
        /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stripe/stripe/0.3.0/docs/resources/setup_intent#billing_agreement_id SetupIntent#billing_agreement_id}
        /// </remarks>
        [JsiiProperty(name: "billingAgreementId", typeJson: "{\"primitive\":\"string\"}", isOptional: true)]
        [Amazon.JSII.Runtime.Deputy.JsiiOptional]
        string? BillingAgreementId
        {
            get
            {
                return null;
            }
        }

        [JsiiTypeProxy(nativeType: typeof(ISetupIntentPaymentMethodOptionsPaypal), fullyQualifiedName: "stripe.setupIntent.SetupIntentPaymentMethodOptionsPaypal")]
        internal sealed class _Proxy : DeputyBase, stripe.SetupIntent.ISetupIntentPaymentMethodOptionsPaypal
        {
            private _Proxy(ByRefValue reference): base(reference)
            {
            }

            /// <summary>The PayPal Billing Agreement ID (BAID).</summary>
            /// <remarks>
            /// This is an ID generated by PayPal which represents the mandate between the merchant and the customer.
            ///
            /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stripe/stripe/0.3.0/docs/resources/setup_intent#billing_agreement_id SetupIntent#billing_agreement_id}
            /// </remarks>
            [JsiiOptional]
            [JsiiProperty(name: "billingAgreementId", typeJson: "{\"primitive\":\"string\"}", isOptional: true)]
            public string? BillingAgreementId
            {
                get => GetInstanceProperty<string?>();
            }
        }
    }
}
