using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseToolsRuntimeDatabaseToolsConnectionCredentials
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseToolsRuntimeDatabaseToolsConnectionCredentials.DataOciDatabaseToolsRuntimeDatabaseToolsConnectionCredentialsCredentialCollectionItems")]
    public class DataOciDatabaseToolsRuntimeDatabaseToolsConnectionCredentialsCredentialCollectionItems : oci.DataOciDatabaseToolsRuntimeDatabaseToolsConnectionCredentials.IDataOciDatabaseToolsRuntimeDatabaseToolsConnectionCredentialsCredentialCollectionItems
    {
    }
}
