using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciTenantmanagercontrolplaneSenderInvitations
{
    [JsiiByValue(fqn: "oci.dataOciTenantmanagercontrolplaneSenderInvitations.DataOciTenantmanagercontrolplaneSenderInvitationsSenderInvitationCollectionItemsInvitationFeatures")]
    public class DataOciTenantmanagercontrolplaneSenderInvitationsSenderInvitationCollectionItemsInvitationFeatures : oci.DataOciTenantmanagercontrolplaneSenderInvitations.IDataOciTenantmanagercontrolplaneSenderInvitationsSenderInvitationCollectionItemsInvitationFeatures
    {
    }
}
