using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciLogAnalyticsNamespaceScheduledTasks
{
    [JsiiByValue(fqn: "oci.dataOciLogAnalyticsNamespaceScheduledTasks.DataOciLogAnalyticsNamespaceScheduledTasksScheduledTaskCollectionItemsActionTemplateDetailsTemplateParams")]
    public class DataOciLogAnalyticsNamespaceScheduledTasksScheduledTaskCollectionItemsActionTemplateDetailsTemplateParams : oci.DataOciLogAnalyticsNamespaceScheduledTasks.IDataOciLogAnalyticsNamespaceScheduledTasksScheduledTaskCollectionItemsActionTemplateDetailsTemplateParams
    {
    }
}
