using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementManagedDatabaseSqlPlanBaselineConfiguration
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementManagedDatabaseSqlPlanBaselineConfiguration.DataOciDatabaseManagementManagedDatabaseSqlPlanBaselineConfigurationAutoCaptureFilters")]
    public class DataOciDatabaseManagementManagedDatabaseSqlPlanBaselineConfigurationAutoCaptureFilters : oci.DataOciDatabaseManagementManagedDatabaseSqlPlanBaselineConfiguration.IDataOciDatabaseManagementManagedDatabaseSqlPlanBaselineConfigurationAutoCaptureFilters
    {
    }
}
