using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseToolsRuntimeDatabaseToolsDatabaseApiGatewayConfigAdvancedProperties
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseToolsRuntimeDatabaseToolsDatabaseApiGatewayConfigAdvancedProperties.DataOciDatabaseToolsRuntimeDatabaseToolsDatabaseApiGatewayConfigAdvancedPropertiesDatabaseToolsDatabaseApiGatewayConfigAdvancedPropertySummaryCollection")]
    public class DataOciDatabaseToolsRuntimeDatabaseToolsDatabaseApiGatewayConfigAdvancedPropertiesDatabaseToolsDatabaseApiGatewayConfigAdvancedPropertySummaryCollection : oci.DataOciDatabaseToolsRuntimeDatabaseToolsDatabaseApiGatewayConfigAdvancedProperties.IDataOciDatabaseToolsRuntimeDatabaseToolsDatabaseApiGatewayConfigAdvancedPropertiesDatabaseToolsDatabaseApiGatewayConfigAdvancedPropertySummaryCollection
    {
    }
}
