using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementManagedDatabaseCursorCacheStatements
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementManagedDatabaseCursorCacheStatements.DataOciDatabaseManagementManagedDatabaseCursorCacheStatementsCursorCacheStatementCollection")]
    public class DataOciDatabaseManagementManagedDatabaseCursorCacheStatementsCursorCacheStatementCollection : oci.DataOciDatabaseManagementManagedDatabaseCursorCacheStatements.IDataOciDatabaseManagementManagedDatabaseCursorCacheStatementsCursorCacheStatementCollection
    {
    }
}
