using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciCoreInstanceConfigurations
{
    [JsiiByValue(fqn: "oci.dataOciCoreInstanceConfigurations.DataOciCoreInstanceConfigurationsInstanceConfigurationsInstanceDetailsLaunchDetailsPreemptibleInstanceConfigPreemptionAction")]
    public class DataOciCoreInstanceConfigurationsInstanceConfigurationsInstanceDetailsLaunchDetailsPreemptibleInstanceConfigPreemptionAction : oci.DataOciCoreInstanceConfigurations.IDataOciCoreInstanceConfigurationsInstanceConfigurationsInstanceDetailsLaunchDetailsPreemptibleInstanceConfigPreemptionAction
    {
    }
}
