using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciFusionAppsFusionEnvironmentRefreshActivities
{
    [JsiiByValue(fqn: "oci.dataOciFusionAppsFusionEnvironmentRefreshActivities.DataOciFusionAppsFusionEnvironmentRefreshActivitiesRefreshActivityCollectionItemsRefreshIssueDetailsListStruct")]
    public class DataOciFusionAppsFusionEnvironmentRefreshActivitiesRefreshActivityCollectionItemsRefreshIssueDetailsListStruct : oci.DataOciFusionAppsFusionEnvironmentRefreshActivities.IDataOciFusionAppsFusionEnvironmentRefreshActivitiesRefreshActivityCollectionItemsRefreshIssueDetailsListStruct
    {
    }
}
