using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementManagedDatabaseSqlTuningAdvisorTasksSqlExecutionPlan
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementManagedDatabaseSqlTuningAdvisorTasksSqlExecutionPlan.DataOciDatabaseManagementManagedDatabaseSqlTuningAdvisorTasksSqlExecutionPlanPlan")]
    public class DataOciDatabaseManagementManagedDatabaseSqlTuningAdvisorTasksSqlExecutionPlanPlan : oci.DataOciDatabaseManagementManagedDatabaseSqlTuningAdvisorTasksSqlExecutionPlan.IDataOciDatabaseManagementManagedDatabaseSqlTuningAdvisorTasksSqlExecutionPlanPlan
    {
    }
}
