using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciGenerativeAiHostedApplicationIams
{
    [JsiiByValue(fqn: "oci.dataOciGenerativeAiHostedApplicationIams.DataOciGenerativeAiHostedApplicationIamsHostedApplicationCollectionItemsNetworkingConfigOutboundNetworkingConfig")]
    public class DataOciGenerativeAiHostedApplicationIamsHostedApplicationCollectionItemsNetworkingConfigOutboundNetworkingConfig : oci.DataOciGenerativeAiHostedApplicationIams.IDataOciGenerativeAiHostedApplicationIamsHostedApplicationCollectionItemsNetworkingConfigOutboundNetworkingConfig
    {
    }
}
