using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementCloudExadataStorageConnectors
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementCloudExadataStorageConnectors.DataOciDatabaseManagementCloudExadataStorageConnectorsCloudExadataStorageConnectorCollectionItems")]
    public class DataOciDatabaseManagementCloudExadataStorageConnectorsCloudExadataStorageConnectorCollectionItems : oci.DataOciDatabaseManagementCloudExadataStorageConnectors.IDataOciDatabaseManagementCloudExadataStorageConnectorsCloudExadataStorageConnectorCollectionItems
    {
    }
}
