using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciGenerativeAiAgentAgentEndpoints
{
    [JsiiByValue(fqn: "oci.dataOciGenerativeAiAgentAgentEndpoints.DataOciGenerativeAiAgentAgentEndpointsAgentEndpointCollectionItemsGuardrailConfigPersonallyIdentifiableInformationConfig")]
    public class DataOciGenerativeAiAgentAgentEndpointsAgentEndpointCollectionItemsGuardrailConfigPersonallyIdentifiableInformationConfig : oci.DataOciGenerativeAiAgentAgentEndpoints.IDataOciGenerativeAiAgentAgentEndpointsAgentEndpointCollectionItemsGuardrailConfigPersonallyIdentifiableInformationConfig
    {
    }
}
