using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDelegateAccessControlDelegationSubscriptions
{
    [JsiiByValue(fqn: "oci.dataOciDelegateAccessControlDelegationSubscriptions.DataOciDelegateAccessControlDelegationSubscriptionsDelegationSubscriptionSummaryCollectionItems")]
    public class DataOciDelegateAccessControlDelegationSubscriptionsDelegationSubscriptionSummaryCollectionItems : oci.DataOciDelegateAccessControlDelegationSubscriptions.IDataOciDelegateAccessControlDelegationSubscriptionsDelegationSubscriptionSummaryCollectionItems
    {
    }
}
