using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatasciencePipelineRuns
{
    [JsiiByValue(fqn: "oci.dataOciDatasciencePipelineRuns.DataOciDatasciencePipelineRunsPipelineRunsStepOverrideDetailsStepDataflowConfigurationDetailsExecutorShapeConfigDetails")]
    public class DataOciDatasciencePipelineRunsPipelineRunsStepOverrideDetailsStepDataflowConfigurationDetailsExecutorShapeConfigDetails : oci.DataOciDatasciencePipelineRuns.IDataOciDatasciencePipelineRunsPipelineRunsStepOverrideDetailsStepDataflowConfigurationDetailsExecutorShapeConfigDetails
    {
    }
}
