using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDbmulticloudOracleDbAzureVaults
{
    [JsiiByValue(fqn: "oci.dataOciDbmulticloudOracleDbAzureVaults.DataOciDbmulticloudOracleDbAzureVaultsOracleDbAzureVaultSummaryCollectionItemsReplicationMetadataReplicationDetails")]
    public class DataOciDbmulticloudOracleDbAzureVaultsOracleDbAzureVaultSummaryCollectionItemsReplicationMetadataReplicationDetails : oci.DataOciDbmulticloudOracleDbAzureVaults.IDataOciDbmulticloudOracleDbAzureVaultsOracleDbAzureVaultSummaryCollectionItemsReplicationMetadataReplicationDetails
    {
    }
}
