using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciOsManagementHubManagedInstanceAvailableSoftwareSources
{
    [JsiiByValue(fqn: "oci.dataOciOsManagementHubManagedInstanceAvailableSoftwareSources.DataOciOsManagementHubManagedInstanceAvailableSoftwareSourcesAvailableSoftwareSourceCollectionItems")]
    public class DataOciOsManagementHubManagedInstanceAvailableSoftwareSourcesAvailableSoftwareSourceCollectionItems : oci.DataOciOsManagementHubManagedInstanceAvailableSoftwareSources.IDataOciOsManagementHubManagedInstanceAvailableSoftwareSourcesAvailableSoftwareSourceCollectionItems
    {
    }
}
