using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciOsManagementHubDynamicSetManagedInstances
{
    [JsiiByValue(fqn: "oci.dataOciOsManagementHubDynamicSetManagedInstances.DataOciOsManagementHubDynamicSetManagedInstancesManagedInstanceCollectionItemsManagedInstanceGroup")]
    public class DataOciOsManagementHubDynamicSetManagedInstancesManagedInstanceCollectionItemsManagedInstanceGroup : oci.DataOciOsManagementHubDynamicSetManagedInstances.IDataOciOsManagementHubDynamicSetManagedInstancesManagedInstanceCollectionItemsManagedInstanceGroup
    {
    }
}
