using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseCloudAutonomousVmClusterResourceUsage
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseCloudAutonomousVmClusterResourceUsage.DataOciDatabaseCloudAutonomousVmClusterResourceUsageAutonomousVmResourceUsageAutonomousContainerDatabaseUsage")]
    public class DataOciDatabaseCloudAutonomousVmClusterResourceUsageAutonomousVmResourceUsageAutonomousContainerDatabaseUsage : oci.DataOciDatabaseCloudAutonomousVmClusterResourceUsage.IDataOciDatabaseCloudAutonomousVmClusterResourceUsageAutonomousVmResourceUsageAutonomousContainerDatabaseUsage
    {
    }
}
