using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementManagedDatabaseOptimizerStatisticsCollectionOperation
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementManagedDatabaseOptimizerStatisticsCollectionOperation.DataOciDatabaseManagementManagedDatabaseOptimizerStatisticsCollectionOperationTasks")]
    public class DataOciDatabaseManagementManagedDatabaseOptimizerStatisticsCollectionOperationTasks : oci.DataOciDatabaseManagementManagedDatabaseOptimizerStatisticsCollectionOperation.IDataOciDatabaseManagementManagedDatabaseOptimizerStatisticsCollectionOperationTasks
    {
    }
}
