using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace scaleway.DataScalewayObjectBucketServerSideEncryptionConfiguration
{
    [JsiiByValue(fqn: "scaleway.dataScalewayObjectBucketServerSideEncryptionConfiguration.DataScalewayObjectBucketServerSideEncryptionConfigurationRuleApplyServerSideEncryptionByDefault")]
    public class DataScalewayObjectBucketServerSideEncryptionConfigurationRuleApplyServerSideEncryptionByDefault : scaleway.DataScalewayObjectBucketServerSideEncryptionConfiguration.IDataScalewayObjectBucketServerSideEncryptionConfigurationRuleApplyServerSideEncryptionByDefault
    {
    }
}
