using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciFleetAppsManagementSchedulerJobJobActivityResources
{
    [JsiiByValue(fqn: "oci.dataOciFleetAppsManagementSchedulerJobJobActivityResources.DataOciFleetAppsManagementSchedulerJobJobActivityResourcesResourceCollectionItemsTargets")]
    public class DataOciFleetAppsManagementSchedulerJobJobActivityResourcesResourceCollectionItemsTargets : oci.DataOciFleetAppsManagementSchedulerJobJobActivityResources.IDataOciFleetAppsManagementSchedulerJobJobActivityResourcesResourceCollectionItemsTargets
    {
    }
}
