using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciOsManagementHubSoftwareSourceModuleStreamProfiles
{
    [JsiiByValue(fqn: "oci.dataOciOsManagementHubSoftwareSourceModuleStreamProfiles.DataOciOsManagementHubSoftwareSourceModuleStreamProfilesModuleStreamProfileCollectionItems")]
    public class DataOciOsManagementHubSoftwareSourceModuleStreamProfilesModuleStreamProfileCollectionItems : oci.DataOciOsManagementHubSoftwareSourceModuleStreamProfiles.IDataOciOsManagementHubSoftwareSourceModuleStreamProfilesModuleStreamProfileCollectionItems
    {
    }
}
