using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDisasterRecoveryDrProtectionGroups
{
    [JsiiByValue(fqn: "oci.dataOciDisasterRecoveryDrProtectionGroups.DataOciDisasterRecoveryDrProtectionGroupsDrProtectionGroupCollectionItemsMembersSourceVolumeToDestinationEncryptionKeyMappingsDestinationEncryptionKey")]
    public class DataOciDisasterRecoveryDrProtectionGroupsDrProtectionGroupCollectionItemsMembersSourceVolumeToDestinationEncryptionKeyMappingsDestinationEncryptionKey : oci.DataOciDisasterRecoveryDrProtectionGroups.IDataOciDisasterRecoveryDrProtectionGroupsDrProtectionGroupCollectionItemsMembersSourceVolumeToDestinationEncryptionKeyMappingsDestinationEncryptionKey
    {
    }
}
