using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementManagedDatabasePreferredCredentials
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementManagedDatabasePreferredCredentials.DataOciDatabaseManagementManagedDatabasePreferredCredentialsPreferredCredentialCollection")]
    public class DataOciDatabaseManagementManagedDatabasePreferredCredentialsPreferredCredentialCollection : oci.DataOciDatabaseManagementManagedDatabasePreferredCredentials.IDataOciDatabaseManagementManagedDatabasePreferredCredentialsPreferredCredentialCollection
    {
    }
}
