using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseAutonomousVmClusterResourceUsage
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseAutonomousVmClusterResourceUsage.DataOciDatabaseAutonomousVmClusterResourceUsageAutonomousVmResourceUsageAutonomousContainerDatabaseUsage")]
    public class DataOciDatabaseAutonomousVmClusterResourceUsageAutonomousVmResourceUsageAutonomousContainerDatabaseUsage : oci.DataOciDatabaseAutonomousVmClusterResourceUsage.IDataOciDatabaseAutonomousVmClusterResourceUsageAutonomousVmResourceUsageAutonomousContainerDatabaseUsage
    {
    }
}
