using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciContainerInstancesContainerInstanceShapes
{
    [JsiiByValue(fqn: "oci.dataOciContainerInstancesContainerInstanceShapes.DataOciContainerInstancesContainerInstanceShapesContainerInstanceShapeCollectionItemsMemoryOptions")]
    public class DataOciContainerInstancesContainerInstanceShapesContainerInstanceShapeCollectionItemsMemoryOptions : oci.DataOciContainerInstancesContainerInstanceShapes.IDataOciContainerInstancesContainerInstanceShapesContainerInstanceShapeCollectionItemsMemoryOptions
    {
    }
}
