using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciStackMonitoringMonitoringTemplateAlarmConditions
{
    [JsiiByValue(fqn: "oci.dataOciStackMonitoringMonitoringTemplateAlarmConditions.DataOciStackMonitoringMonitoringTemplateAlarmConditionsAlarmConditionCollectionItemsConditions")]
    public class DataOciStackMonitoringMonitoringTemplateAlarmConditionsAlarmConditionCollectionItemsConditions : oci.DataOciStackMonitoringMonitoringTemplateAlarmConditions.IDataOciStackMonitoringMonitoringTemplateAlarmConditionsAlarmConditionCollectionItemsConditions
    {
    }
}
