using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseSchedulingPolicyRecommendedScheduledActions
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseSchedulingPolicyRecommendedScheduledActions.DataOciDatabaseSchedulingPolicyRecommendedScheduledActionsRecommendedScheduledActionsCollectionItemsActionMembers")]
    public class DataOciDatabaseSchedulingPolicyRecommendedScheduledActionsRecommendedScheduledActionsCollectionItemsActionMembers : oci.DataOciDatabaseSchedulingPolicyRecommendedScheduledActions.IDataOciDatabaseSchedulingPolicyRecommendedScheduledActionsRecommendedScheduledActionsCollectionItemsActionMembers
    {
    }
}
