using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciMeteringComputationUsageStatementEmailRecipientsGroups
{
    [JsiiByValue(fqn: "oci.dataOciMeteringComputationUsageStatementEmailRecipientsGroups.DataOciMeteringComputationUsageStatementEmailRecipientsGroupsEmailRecipientsGroupCollection")]
    public class DataOciMeteringComputationUsageStatementEmailRecipientsGroupsEmailRecipientsGroupCollection : oci.DataOciMeteringComputationUsageStatementEmailRecipientsGroups.IDataOciMeteringComputationUsageStatementEmailRecipientsGroupsEmailRecipientsGroupCollection
    {
    }
}
