using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciMeteringComputationUsageStatementEmailRecipientsGroups
{
    [JsiiByValue(fqn: "oci.dataOciMeteringComputationUsageStatementEmailRecipientsGroups.DataOciMeteringComputationUsageStatementEmailRecipientsGroupsEmailRecipientsGroupCollectionItems")]
    public class DataOciMeteringComputationUsageStatementEmailRecipientsGroupsEmailRecipientsGroupCollectionItems : oci.DataOciMeteringComputationUsageStatementEmailRecipientsGroups.IDataOciMeteringComputationUsageStatementEmailRecipientsGroupsEmailRecipientsGroupCollectionItems
    {
    }
}
