using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementManagedDatabaseSqlPlanBaselineJobs
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementManagedDatabaseSqlPlanBaselineJobs.DataOciDatabaseManagementManagedDatabaseSqlPlanBaselineJobsSqlPlanBaselineJobCollectionItems")]
    public class DataOciDatabaseManagementManagedDatabaseSqlPlanBaselineJobsSqlPlanBaselineJobCollectionItems : oci.DataOciDatabaseManagementManagedDatabaseSqlPlanBaselineJobs.IDataOciDatabaseManagementManagedDatabaseSqlPlanBaselineJobsSqlPlanBaselineJobCollectionItems
    {
    }
}
