using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciNetworkFirewallNetworkFirewallPolicySecurityRules
{
    [JsiiByValue(fqn: "oci.dataOciNetworkFirewallNetworkFirewallPolicySecurityRules.DataOciNetworkFirewallNetworkFirewallPolicySecurityRulesSecurityRuleSummaryCollectionItemsCondition")]
    public class DataOciNetworkFirewallNetworkFirewallPolicySecurityRulesSecurityRuleSummaryCollectionItemsCondition : oci.DataOciNetworkFirewallNetworkFirewallPolicySecurityRules.IDataOciNetworkFirewallNetworkFirewallPolicySecurityRulesSecurityRuleSummaryCollectionItemsCondition
    {
    }
}
