using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciCapacityManagementInternalOccmDemandSignalCatalogs
{
    [JsiiByValue(fqn: "oci.dataOciCapacityManagementInternalOccmDemandSignalCatalogs.DataOciCapacityManagementInternalOccmDemandSignalCatalogsOccmDemandSignalCatalogCollectionItems")]
    public class DataOciCapacityManagementInternalOccmDemandSignalCatalogsOccmDemandSignalCatalogCollectionItems : oci.DataOciCapacityManagementInternalOccmDemandSignalCatalogs.IDataOciCapacityManagementInternalOccmDemandSignalCatalogsOccmDemandSignalCatalogCollectionItems
    {
    }
}
