using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace stripe.Quote
{
    [JsiiByValue(fqn: "stripe.quote.QuoteInvoiceSettings")]
    public class QuoteInvoiceSettings : stripe.Quote.IQuoteInvoiceSettings
    {
        /// <summary>Number of days within which a customer must pay invoices generated by this quote.</summary>
        /// <remarks>
        /// This value will be <c>null</c> for quotes where <c>collection_method=charge_automatically</c>.
        ///
        /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stripe/stripe/0.3.0/docs/resources/quote#days_until_due Quote#days_until_due}
        /// </remarks>
        [JsiiOptional]
        [JsiiProperty(name: "daysUntilDue", typeJson: "{\"primitive\":\"number\"}", isOptional: true)]
        public double? DaysUntilDue
        {
            get;
            set;
        }

        /// <summary>Docs at Terraform Registry: {@link https://registry.terraform.io/providers/stripe/stripe/0.3.0/docs/resources/quote#issuer Quote#issuer}.</summary>
        [JsiiOptional]
        [JsiiProperty(name: "issuer", typeJson: "{\"fqn\":\"stripe.quote.QuoteInvoiceSettingsIssuer\"}", isOptional: true)]
        public stripe.Quote.IQuoteInvoiceSettingsIssuer? Issuer
        {
            get;
            set;
        }
    }
}
