using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciAdmRemediationRunApplicationDependencyRecommendations
{
    [JsiiByValue(fqn: "oci.dataOciAdmRemediationRunApplicationDependencyRecommendations.DataOciAdmRemediationRunApplicationDependencyRecommendationsApplicationDependencyRecommendationCollection")]
    public class DataOciAdmRemediationRunApplicationDependencyRecommendationsApplicationDependencyRecommendationCollection : oci.DataOciAdmRemediationRunApplicationDependencyRecommendations.IDataOciAdmRemediationRunApplicationDependencyRecommendationsApplicationDependencyRecommendationCollection
    {
    }
}
