using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementManagedDatabasesUserSystemPrivileges
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementManagedDatabasesUserSystemPrivileges.DataOciDatabaseManagementManagedDatabasesUserSystemPrivilegesSystemPrivilegeCollection")]
    public class DataOciDatabaseManagementManagedDatabasesUserSystemPrivilegesSystemPrivilegeCollection : oci.DataOciDatabaseManagementManagedDatabasesUserSystemPrivileges.IDataOciDatabaseManagementManagedDatabasesUserSystemPrivilegesSystemPrivilegeCollection
    {
    }
}
