using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciIdentityDomainsIdentityProofingProviderTemplates
{
    [JsiiByValue(fqn: "oci.dataOciIdentityDomainsIdentityProofingProviderTemplates.DataOciIdentityDomainsIdentityProofingProviderTemplatesIdentityProofingProviderTemplatesIdcsLockedBy")]
    public class DataOciIdentityDomainsIdentityProofingProviderTemplatesIdentityProofingProviderTemplatesIdcsLockedBy : oci.DataOciIdentityDomainsIdentityProofingProviderTemplates.IDataOciIdentityDomainsIdentityProofingProviderTemplatesIdentityProofingProviderTemplatesIdcsLockedBy
    {
    }
}
