using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementExternalMySqlDatabaseConnectors
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementExternalMySqlDatabaseConnectors.DataOciDatabaseManagementExternalMySqlDatabaseConnectorsMySqlConnectorCollectionItemsConnectorDetails")]
    public class DataOciDatabaseManagementExternalMySqlDatabaseConnectorsMySqlConnectorCollectionItemsConnectorDetails : oci.DataOciDatabaseManagementExternalMySqlDatabaseConnectors.IDataOciDatabaseManagementExternalMySqlDatabaseConnectorsMySqlConnectorCollectionItemsConnectorDetails
    {
    }
}
