using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDataintegrationWorkspaceTasks
{
    [JsiiByValue(fqn: "oci.dataOciDataintegrationWorkspaceTasks.DataOciDataintegrationWorkspaceTasksTaskSummaryCollectionItemsPollRestCallConfigConfigValuesConfigParamValuesPollMaxDuration")]
    public class DataOciDataintegrationWorkspaceTasksTaskSummaryCollectionItemsPollRestCallConfigConfigValuesConfigParamValuesPollMaxDuration : oci.DataOciDataintegrationWorkspaceTasks.IDataOciDataintegrationWorkspaceTasksTaskSummaryCollectionItemsPollRestCallConfigConfigValuesConfigParamValuesPollMaxDuration
    {
    }
}
