using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DatabaseManagementCloudDbSystemDiscovery
{
    [JsiiByValue(fqn: "oci.databaseManagementCloudDbSystemDiscovery.DatabaseManagementCloudDbSystemDiscoveryDiscoveredComponentsClusterInstancesConnectorConnectionInfoConnectionString")]
    public class DatabaseManagementCloudDbSystemDiscoveryDiscoveredComponentsClusterInstancesConnectorConnectionInfoConnectionString : oci.DatabaseManagementCloudDbSystemDiscovery.IDatabaseManagementCloudDbSystemDiscoveryDiscoveredComponentsClusterInstancesConnectorConnectionInfoConnectionString
    {
    }
}
