using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDbmulticloudMultiCloudResourceDiscoveries
{
    [JsiiByValue(fqn: "oci.dataOciDbmulticloudMultiCloudResourceDiscoveries.DataOciDbmulticloudMultiCloudResourceDiscoveriesMultiCloudResourceDiscoverySummaryCollectionItemsResources")]
    public class DataOciDbmulticloudMultiCloudResourceDiscoveriesMultiCloudResourceDiscoverySummaryCollectionItemsResources : oci.DataOciDbmulticloudMultiCloudResourceDiscoveries.IDataOciDbmulticloudMultiCloudResourceDiscoveriesMultiCloudResourceDiscoverySummaryCollectionItemsResources
    {
    }
}
