using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciCapacityManagementInternalOccmDemandSignalCatalogResources
{
    [JsiiByValue(fqn: "oci.dataOciCapacityManagementInternalOccmDemandSignalCatalogResources.DataOciCapacityManagementInternalOccmDemandSignalCatalogResourcesInternalOccmDemandSignalCatalogResourceCollectionItemsResourcePropertiesItems")]
    public class DataOciCapacityManagementInternalOccmDemandSignalCatalogResourcesInternalOccmDemandSignalCatalogResourceCollectionItemsResourcePropertiesItems : oci.DataOciCapacityManagementInternalOccmDemandSignalCatalogResources.IDataOciCapacityManagementInternalOccmDemandSignalCatalogResourcesInternalOccmDemandSignalCatalogResourceCollectionItemsResourcePropertiesItems
    {
    }
}
