using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace libvirt.Network
{
    [JsiiInterface(nativeType: typeof(INetworkBridge), fullyQualifiedName: "libvirt.network.NetworkBridge")]
    public interface INetworkBridge
    {
        /// <summary>Sets the forwarding delay (in seconds) for the bridge, controlling how long ports stay in the listening/learning states when STP is enabled;</summary>
        /// <remarks>
        /// value is a user-provided non-negative integer.
        ///
        /// See: <a href="https://libvirt.org/formatnetwork.html#connectivity">https://libvirt.org/formatnetwork.html#connectivity</a>
        ///
        /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/dmacvicar/libvirt/0.9.8/docs/resources/network#delay Network#delay}
        /// </remarks>
        [JsiiProperty(name: "delay", typeJson: "{\"primitive\":\"string\"}", isOptional: true)]
        [Amazon.JSII.Runtime.Deputy.JsiiOptional]
        string? Delay
        {
            get
            {
                return null;
            }
        }

        /// <summary>Selects the MAC address table manager implementation for the bridge (e.g. "kernel" or "libvirt" when supported); value is a user-provided string constrained to backend-supported options.</summary>
        /// <remarks>
        /// See: <a href="https://libvirt.org/formatnetwork.html#connectivity">https://libvirt.org/formatnetwork.html#connectivity</a>
        ///
        /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/dmacvicar/libvirt/0.9.8/docs/resources/network#mac_table_manager Network#mac_table_manager}
        /// </remarks>
        [JsiiProperty(name: "macTableManager", typeJson: "{\"primitive\":\"string\"}", isOptional: true)]
        [Amazon.JSII.Runtime.Deputy.JsiiOptional]
        string? MacTableManager
        {
            get
            {
                return null;
            }
        }

        /// <summary>Bridge name (generated by libvirt if not specified).</summary>
        /// <remarks>
        /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/dmacvicar/libvirt/0.9.8/docs/resources/network#name Network#name}
        /// </remarks>
        [JsiiProperty(name: "name", typeJson: "{\"primitive\":\"string\"}", isOptional: true)]
        [Amazon.JSII.Runtime.Deputy.JsiiOptional]
        string? Name
        {
            get
            {
                return null;
            }
        }

        /// <summary>Enables or disables Spanning Tree Protocol on the bridge; accepts the strings "on" or "off".</summary>
        /// <remarks>
        /// See: <a href="https://libvirt.org/formatnetwork.html#connectivity">https://libvirt.org/formatnetwork.html#connectivity</a>
        ///
        /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/dmacvicar/libvirt/0.9.8/docs/resources/network#stp Network#stp}
        /// </remarks>
        [JsiiProperty(name: "stp", typeJson: "{\"primitive\":\"string\"}", isOptional: true)]
        [Amazon.JSII.Runtime.Deputy.JsiiOptional]
        string? Stp
        {
            get
            {
                return null;
            }
        }

        /// <summary>Sets the DNS zone name associated with the bridged network, used as the default domain for DNS records served by this network.</summary>
        /// <remarks>
        /// The value is user-provided and should typically be a valid DNS domain name (e.g. "example.local").
        ///
        /// See: <a href="https://libvirt.org/formatnetwork.html#connectivity">https://libvirt.org/formatnetwork.html#connectivity</a>
        ///
        /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/dmacvicar/libvirt/0.9.8/docs/resources/network#zone Network#zone}
        /// </remarks>
        [JsiiProperty(name: "zone", typeJson: "{\"primitive\":\"string\"}", isOptional: true)]
        [Amazon.JSII.Runtime.Deputy.JsiiOptional]
        string? Zone
        {
            get
            {
                return null;
            }
        }

        [JsiiTypeProxy(nativeType: typeof(INetworkBridge), fullyQualifiedName: "libvirt.network.NetworkBridge")]
        internal sealed class _Proxy : DeputyBase, libvirt.Network.INetworkBridge
        {
            private _Proxy(ByRefValue reference): base(reference)
            {
            }

            /// <summary>Sets the forwarding delay (in seconds) for the bridge, controlling how long ports stay in the listening/learning states when STP is enabled;</summary>
            /// <remarks>
            /// value is a user-provided non-negative integer.
            ///
            /// See: <a href="https://libvirt.org/formatnetwork.html#connectivity">https://libvirt.org/formatnetwork.html#connectivity</a>
            ///
            /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/dmacvicar/libvirt/0.9.8/docs/resources/network#delay Network#delay}
            /// </remarks>
            [JsiiOptional]
            [JsiiProperty(name: "delay", typeJson: "{\"primitive\":\"string\"}", isOptional: true)]
            public string? Delay
            {
                get => GetInstanceProperty<string?>();
            }

            /// <summary>Selects the MAC address table manager implementation for the bridge (e.g. "kernel" or "libvirt" when supported); value is a user-provided string constrained to backend-supported options.</summary>
            /// <remarks>
            /// See: <a href="https://libvirt.org/formatnetwork.html#connectivity">https://libvirt.org/formatnetwork.html#connectivity</a>
            ///
            /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/dmacvicar/libvirt/0.9.8/docs/resources/network#mac_table_manager Network#mac_table_manager}
            /// </remarks>
            [JsiiOptional]
            [JsiiProperty(name: "macTableManager", typeJson: "{\"primitive\":\"string\"}", isOptional: true)]
            public string? MacTableManager
            {
                get => GetInstanceProperty<string?>();
            }

            /// <summary>Bridge name (generated by libvirt if not specified).</summary>
            /// <remarks>
            /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/dmacvicar/libvirt/0.9.8/docs/resources/network#name Network#name}
            /// </remarks>
            [JsiiOptional]
            [JsiiProperty(name: "name", typeJson: "{\"primitive\":\"string\"}", isOptional: true)]
            public string? Name
            {
                get => GetInstanceProperty<string?>();
            }

            /// <summary>Enables or disables Spanning Tree Protocol on the bridge; accepts the strings "on" or "off".</summary>
            /// <remarks>
            /// See: <a href="https://libvirt.org/formatnetwork.html#connectivity">https://libvirt.org/formatnetwork.html#connectivity</a>
            ///
            /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/dmacvicar/libvirt/0.9.8/docs/resources/network#stp Network#stp}
            /// </remarks>
            [JsiiOptional]
            [JsiiProperty(name: "stp", typeJson: "{\"primitive\":\"string\"}", isOptional: true)]
            public string? Stp
            {
                get => GetInstanceProperty<string?>();
            }

            /// <summary>Sets the DNS zone name associated with the bridged network, used as the default domain for DNS records served by this network.</summary>
            /// <remarks>
            /// The value is user-provided and should typically be a valid DNS domain name (e.g. "example.local").
            ///
            /// See: <a href="https://libvirt.org/formatnetwork.html#connectivity">https://libvirt.org/formatnetwork.html#connectivity</a>
            ///
            /// Docs at Terraform Registry: {@link https://registry.terraform.io/providers/dmacvicar/libvirt/0.9.8/docs/resources/network#zone Network#zone}
            /// </remarks>
            [JsiiOptional]
            [JsiiProperty(name: "zone", typeJson: "{\"primitive\":\"string\"}", isOptional: true)]
            public string? Zone
            {
                get => GetInstanceProperty<string?>();
            }
        }
    }
}
