using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciStackMonitoringMonitoredResourceTypes
{
    [JsiiByValue(fqn: "oci.dataOciStackMonitoringMonitoredResourceTypes.DataOciStackMonitoringMonitoredResourceTypesMonitoredResourceTypesCollectionItemsHandlerConfigMetricNameConfig")]
    public class DataOciStackMonitoringMonitoredResourceTypesMonitoredResourceTypesCollectionItemsHandlerConfigMetricNameConfig : oci.DataOciStackMonitoringMonitoredResourceTypes.IDataOciStackMonitoringMonitoredResourceTypesMonitoredResourceTypesCollectionItemsHandlerConfigMetricNameConfig
    {
    }
}
