using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementCloudDbSystemDiscovery
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementCloudDbSystemDiscovery.DataOciDatabaseManagementCloudDbSystemDiscoveryDiscoveredComponentsConnectorConnectionInfoConnectionString")]
    public class DataOciDatabaseManagementCloudDbSystemDiscoveryDiscoveredComponentsConnectorConnectionInfoConnectionString : oci.DataOciDatabaseManagementCloudDbSystemDiscovery.IDataOciDatabaseManagementCloudDbSystemDiscoveryDiscoveredComponentsConnectorConnectionInfoConnectionString
    {
    }
}
