using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseMaintenanceRunHistories
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseMaintenanceRunHistories.DataOciDatabaseMaintenanceRunHistoriesMaintenanceRunHistoriesGranularMaintenanceHistoryExecutionActionsActionMembers")]
    public class DataOciDatabaseMaintenanceRunHistoriesMaintenanceRunHistoriesGranularMaintenanceHistoryExecutionActionsActionMembers : oci.DataOciDatabaseMaintenanceRunHistories.IDataOciDatabaseMaintenanceRunHistoriesMaintenanceRunHistoriesGranularMaintenanceHistoryExecutionActionsActionMembers
    {
    }
}
