using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciOperatorAccessControlOperatorControlAssignments
{
    [JsiiByValue(fqn: "oci.dataOciOperatorAccessControlOperatorControlAssignments.DataOciOperatorAccessControlOperatorControlAssignmentsOperatorControlAssignmentCollectionItems")]
    public class DataOciOperatorAccessControlOperatorControlAssignmentsOperatorControlAssignmentCollectionItems : oci.DataOciOperatorAccessControlOperatorControlAssignments.IDataOciOperatorAccessControlOperatorControlAssignmentsOperatorControlAssignmentCollectionItems
    {
    }
}
