using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementCloudDbSystemConnectors
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementCloudDbSystemConnectors.DataOciDatabaseManagementCloudDbSystemConnectorsCloudDbSystemConnectorCollectionItemsConnectionInfo")]
    public class DataOciDatabaseManagementCloudDbSystemConnectorsCloudDbSystemConnectorCollectionItemsConnectionInfo : oci.DataOciDatabaseManagementCloudDbSystemConnectors.IDataOciDatabaseManagementCloudDbSystemConnectorsCloudDbSystemConnectorCollectionItemsConnectionInfo
    {
    }
}
