using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciBdsBdsCapacityReservationAssociatedConfigurations
{
    [JsiiByValue(fqn: "oci.dataOciBdsBdsCapacityReservationAssociatedConfigurations.DataOciBdsBdsCapacityReservationAssociatedConfigurationsBdsCapacityReservationAssociatedConfigurationCollectionItems")]
    public class DataOciBdsBdsCapacityReservationAssociatedConfigurationsBdsCapacityReservationAssociatedConfigurationCollectionItems : oci.DataOciBdsBdsCapacityReservationAssociatedConfigurations.IDataOciBdsBdsCapacityReservationAssociatedConfigurationsBdsCapacityReservationAssociatedConfigurationCollectionItems
    {
    }
}
