using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciFleetAppsManagementPlatformConfigurations
{
    [JsiiByValue(fqn: "oci.dataOciFleetAppsManagementPlatformConfigurations.DataOciFleetAppsManagementPlatformConfigurationsPlatformConfigurationCollectionItemsConfigCategoryDetailsCredentials")]
    public class DataOciFleetAppsManagementPlatformConfigurationsPlatformConfigurationCollectionItemsConfigCategoryDetailsCredentials : oci.DataOciFleetAppsManagementPlatformConfigurations.IDataOciFleetAppsManagementPlatformConfigurationsPlatformConfigurationCollectionItemsConfigCategoryDetailsCredentials
    {
    }
}
