using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciFleetAppsManagementPlatformConfigurations
{
    [JsiiByValue(fqn: "oci.dataOciFleetAppsManagementPlatformConfigurations.DataOciFleetAppsManagementPlatformConfigurationsPlatformConfigurationCollectionItemsConfigCategoryDetailsSubCategoryDetailsPatchTypes")]
    public class DataOciFleetAppsManagementPlatformConfigurationsPlatformConfigurationCollectionItemsConfigCategoryDetailsSubCategoryDetailsPatchTypes : oci.DataOciFleetAppsManagementPlatformConfigurations.IDataOciFleetAppsManagementPlatformConfigurationsPlatformConfigurationCollectionItemsConfigCategoryDetailsSubCategoryDetailsPatchTypes
    {
    }
}
