using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciCapacityManagementOccmDemandSignalCatalogResources
{
    [JsiiByValue(fqn: "oci.dataOciCapacityManagementOccmDemandSignalCatalogResources.DataOciCapacityManagementOccmDemandSignalCatalogResourcesOccmDemandSignalCatalogResourceCollectionItemsResourcePropertyConstraints")]
    public class DataOciCapacityManagementOccmDemandSignalCatalogResourcesOccmDemandSignalCatalogResourceCollectionItemsResourcePropertyConstraints : oci.DataOciCapacityManagementOccmDemandSignalCatalogResources.IDataOciCapacityManagementOccmDemandSignalCatalogResourcesOccmDemandSignalCatalogResourceCollectionItemsResourcePropertyConstraints
    {
    }
}
