using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciCapacityManagementOccmDemandSignalCatalogResources
{
    [JsiiByValue(fqn: "oci.dataOciCapacityManagementOccmDemandSignalCatalogResources.DataOciCapacityManagementOccmDemandSignalCatalogResourcesOccmDemandSignalCatalogResourceCollectionItemsResourcePropertyConstraintsItems")]
    public class DataOciCapacityManagementOccmDemandSignalCatalogResourcesOccmDemandSignalCatalogResourceCollectionItemsResourcePropertyConstraintsItems : oci.DataOciCapacityManagementOccmDemandSignalCatalogResources.IDataOciCapacityManagementOccmDemandSignalCatalogResourcesOccmDemandSignalCatalogResourceCollectionItemsResourcePropertyConstraintsItems
    {
    }
}
