using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementExternalDbSystemConnectors
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementExternalDbSystemConnectors.DataOciDatabaseManagementExternalDbSystemConnectorsExternalDbSystemConnectorCollectionItemsConnectionInfoDatabaseCredential")]
    public class DataOciDatabaseManagementExternalDbSystemConnectorsExternalDbSystemConnectorCollectionItemsConnectionInfoDatabaseCredential : oci.DataOciDatabaseManagementExternalDbSystemConnectors.IDataOciDatabaseManagementExternalDbSystemConnectorsExternalDbSystemConnectorCollectionItemsConnectionInfoDatabaseCredential
    {
    }
}
