using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementCloudDatabases
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementCloudDatabases.DataOciDatabaseManagementCloudDatabasesCloudDatabaseCollectionItemsDbmgmtFeatureConfigsDatabaseConnectionDetails")]
    public class DataOciDatabaseManagementCloudDatabasesCloudDatabaseCollectionItemsDbmgmtFeatureConfigsDatabaseConnectionDetails : oci.DataOciDatabaseManagementCloudDatabases.IDataOciDatabaseManagementCloudDatabasesCloudDatabaseCollectionItemsDbmgmtFeatureConfigsDatabaseConnectionDetails
    {
    }
}
