using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseMigrationAssessmentAssessorCheckAffectedObjects
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseMigrationAssessmentAssessorCheckAffectedObjects.DataOciDatabaseMigrationAssessmentAssessorCheckAffectedObjectsAffectedObjectsCollectionItems")]
    public class DataOciDatabaseMigrationAssessmentAssessorCheckAffectedObjectsAffectedObjectsCollectionItems : oci.DataOciDatabaseMigrationAssessmentAssessorCheckAffectedObjects.IDataOciDatabaseMigrationAssessmentAssessorCheckAffectedObjectsAffectedObjectsCollectionItems
    {
    }
}
