using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciApigatewayApiDeploymentSpecification
{
    [JsiiByValue(fqn: "oci.dataOciApigatewayApiDeploymentSpecification.DataOciApigatewayApiDeploymentSpecificationRoutesRequestPoliciesHeaderTransformationsRenameHeadersItems")]
    public class DataOciApigatewayApiDeploymentSpecificationRoutesRequestPoliciesHeaderTransformationsRenameHeadersItems : oci.DataOciApigatewayApiDeploymentSpecification.IDataOciApigatewayApiDeploymentSpecificationRoutesRequestPoliciesHeaderTransformationsRenameHeadersItems
    {
    }
}
