using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciFleetSoftwareUpdateFsuCollections
{
    [JsiiByValue(fqn: "oci.dataOciFleetSoftwareUpdateFsuCollections.DataOciFleetSoftwareUpdateFsuCollectionsFsuCollectionSummaryCollectionItemsComponentsFleetDiscoveryFilters")]
    public class DataOciFleetSoftwareUpdateFsuCollectionsFsuCollectionSummaryCollectionItemsComponentsFleetDiscoveryFilters : oci.DataOciFleetSoftwareUpdateFsuCollections.IDataOciFleetSoftwareUpdateFsuCollectionsFsuCollectionSummaryCollectionItemsComponentsFleetDiscoveryFilters
    {
    }
}
