using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementExternalExadataStorageServers
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementExternalExadataStorageServers.DataOciDatabaseManagementExternalExadataStorageServersExternalExadataStorageServerCollectionItems")]
    public class DataOciDatabaseManagementExternalExadataStorageServersExternalExadataStorageServerCollectionItems : oci.DataOciDatabaseManagementExternalExadataStorageServers.IDataOciDatabaseManagementExternalExadataStorageServersExternalExadataStorageServerCollectionItems
    {
    }
}
