using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDistributedDatabaseDistributedDatabases
{
    [JsiiByValue(fqn: "oci.dataOciDistributedDatabaseDistributedDatabases.DataOciDistributedDatabaseDistributedDatabasesDistributedDatabaseCollectionItemsCatalogDetailsPeerDetails")]
    public class DataOciDistributedDatabaseDistributedDatabasesDistributedDatabaseCollectionItemsCatalogDetailsPeerDetails : oci.DataOciDistributedDatabaseDistributedDatabases.IDataOciDistributedDatabaseDistributedDatabasesDistributedDatabaseCollectionItemsCatalogDetailsPeerDetails
    {
    }
}
