using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDistributedDatabaseDistributedDatabases
{
    [JsiiByValue(fqn: "oci.dataOciDistributedDatabaseDistributedDatabases.DataOciDistributedDatabaseDistributedDatabasesDistributedDatabaseCollectionItemsShardDetailsPeerDetailsDbStorageVaultDetails")]
    public class DataOciDistributedDatabaseDistributedDatabasesDistributedDatabaseCollectionItemsShardDetailsPeerDetailsDbStorageVaultDetails : oci.DataOciDistributedDatabaseDistributedDatabases.IDataOciDistributedDatabaseDistributedDatabasesDistributedDatabaseCollectionItemsShardDetailsPeerDetailsDbStorageVaultDetails
    {
    }
}
