using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDistributedDatabaseDistributedDatabases
{
    [JsiiByValue(fqn: "oci.dataOciDistributedDatabaseDistributedDatabases.DataOciDistributedDatabaseDistributedDatabasesDistributedDatabaseCollectionItemsDbBackupConfigBackupDestinationDetails")]
    public class DataOciDistributedDatabaseDistributedDatabasesDistributedDatabaseCollectionItemsDbBackupConfigBackupDestinationDetails : oci.DataOciDistributedDatabaseDistributedDatabases.IDataOciDistributedDatabaseDistributedDatabasesDistributedDatabaseCollectionItemsDbBackupConfigBackupDestinationDetails
    {
    }
}
