using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciFleetAppsManagementRunbooks
{
    [JsiiByValue(fqn: "oci.dataOciFleetAppsManagementRunbooks.DataOciFleetAppsManagementRunbooksRunbookCollectionItemsRunbookVersionTasksTaskRecordDetailsExecutionDetailsCredentials")]
    public class DataOciFleetAppsManagementRunbooksRunbookCollectionItemsRunbookVersionTasksTaskRecordDetailsExecutionDetailsCredentials : oci.DataOciFleetAppsManagementRunbooks.IDataOciFleetAppsManagementRunbooksRunbookCollectionItemsRunbookVersionTasksTaskRecordDetailsExecutionDetailsCredentials
    {
    }
}
