using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementManagedMySqlDatabaseInboundReplications
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementManagedMySqlDatabaseInboundReplications.DataOciDatabaseManagementManagedMySqlDatabaseInboundReplicationsManagedMySqlDatabaseInboundReplicationCollectionItemsFetchError")]
    public class DataOciDatabaseManagementManagedMySqlDatabaseInboundReplicationsManagedMySqlDatabaseInboundReplicationCollectionItemsFetchError : oci.DataOciDatabaseManagementManagedMySqlDatabaseInboundReplications.IDataOciDatabaseManagementManagedMySqlDatabaseInboundReplicationsManagedMySqlDatabaseInboundReplicationCollectionItemsFetchError
    {
    }
}
