using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementCloudExadataInfrastructures
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementCloudExadataInfrastructures.DataOciDatabaseManagementCloudExadataInfrastructuresCloudExadataInfrastructureCollectionItemsVmClusters")]
    public class DataOciDatabaseManagementCloudExadataInfrastructuresCloudExadataInfrastructureCollectionItemsVmClusters : oci.DataOciDatabaseManagementCloudExadataInfrastructures.IDataOciDatabaseManagementCloudExadataInfrastructuresCloudExadataInfrastructureCollectionItemsVmClusters
    {
    }
}
