using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementCloudExadataInfrastructures
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementCloudExadataInfrastructures.DataOciDatabaseManagementCloudExadataInfrastructuresCloudExadataInfrastructureCollectionItemsStorageGrid")]
    public class DataOciDatabaseManagementCloudExadataInfrastructuresCloudExadataInfrastructureCollectionItemsStorageGrid : oci.DataOciDatabaseManagementCloudExadataInfrastructures.IDataOciDatabaseManagementCloudExadataInfrastructuresCloudExadataInfrastructureCollectionItemsStorageGrid
    {
    }
}
