using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseMigrationConnectionDatabaseconnectiontypes
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseMigrationConnectionDatabaseconnectiontypes.DataOciDatabaseMigrationConnectionDatabaseconnectiontypesDatabaseConnectionTypeCollection")]
    public class DataOciDatabaseMigrationConnectionDatabaseconnectiontypesDatabaseConnectionTypeCollection : oci.DataOciDatabaseMigrationConnectionDatabaseconnectiontypes.IDataOciDatabaseMigrationConnectionDatabaseconnectiontypesDatabaseConnectionTypeCollection
    {
    }
}
