using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementExadataInfrastructureFleetMetric
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementExadataInfrastructureFleetMetric.DataOciDatabaseManagementExadataInfrastructureFleetMetricFleetExadataInfrastructuresMetricsDimensions")]
    public class DataOciDatabaseManagementExadataInfrastructureFleetMetricFleetExadataInfrastructuresMetricsDimensions : oci.DataOciDatabaseManagementExadataInfrastructureFleetMetric.IDataOciDatabaseManagementExadataInfrastructureFleetMetricFleetExadataInfrastructuresMetricsDimensions
    {
    }
}
