using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciGenerativeAiProjects
{
    [JsiiByValue(fqn: "oci.dataOciGenerativeAiProjects.DataOciGenerativeAiProjectsGenerativeAiProjectCollectionItemsShortTermMemoryOptimizationConfigCondenserConfigLlmSelection")]
    public class DataOciGenerativeAiProjectsGenerativeAiProjectCollectionItemsShortTermMemoryOptimizationConfigCondenserConfigLlmSelection : oci.DataOciGenerativeAiProjects.IDataOciGenerativeAiProjectsGenerativeAiProjectCollectionItemsShortTermMemoryOptimizationConfigCondenserConfigLlmSelection
    {
    }
}
