using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciCapacityManagementInternalOccHandoverResourceBlocks
{
    [JsiiByValue(fqn: "oci.dataOciCapacityManagementInternalOccHandoverResourceBlocks.DataOciCapacityManagementInternalOccHandoverResourceBlocksOccHandoverResourceBlockCollection")]
    public class DataOciCapacityManagementInternalOccHandoverResourceBlocksOccHandoverResourceBlockCollection : oci.DataOciCapacityManagementInternalOccHandoverResourceBlocks.IDataOciCapacityManagementInternalOccHandoverResourceBlocksOccHandoverResourceBlockCollection
    {
    }
}
