using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace digitalocean.DataDigitaloceanAgentPlatformKnowledgeBaseDataSources
{
    [JsiiByValue(fqn: "digitalocean.dataDigitaloceanAgentPlatformKnowledgeBaseDataSources.DataDigitaloceanAgentPlatformKnowledgeBaseDataSourcesDatasourcesWebCrawlerDataSource")]
    public class DataDigitaloceanAgentPlatformKnowledgeBaseDataSourcesDatasourcesWebCrawlerDataSource : digitalocean.DataDigitaloceanAgentPlatformKnowledgeBaseDataSources.IDataDigitaloceanAgentPlatformKnowledgeBaseDataSourcesDatasourcesWebCrawlerDataSource
    {
    }
}
