using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciMulticloudExternalLocationSummariesMetadata
{
    [JsiiByValue(fqn: "oci.dataOciMulticloudExternalLocationSummariesMetadata.DataOciMulticloudExternalLocationSummariesMetadataExternalLocationSummariesMetadatumSummaryCollectionItemsExternalLocation")]
    public class DataOciMulticloudExternalLocationSummariesMetadataExternalLocationSummariesMetadatumSummaryCollectionItemsExternalLocation : oci.DataOciMulticloudExternalLocationSummariesMetadata.IDataOciMulticloudExternalLocationSummariesMetadataExternalLocationSummariesMetadatumSummaryCollectionItemsExternalLocation
    {
    }
}
