using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciMulticloudExternalLocationSummariesMetadata
{
    [JsiiByValue(fqn: "oci.dataOciMulticloudExternalLocationSummariesMetadata.DataOciMulticloudExternalLocationSummariesMetadataExternalLocationSummariesMetadatumSummaryCollection")]
    public class DataOciMulticloudExternalLocationSummariesMetadataExternalLocationSummariesMetadatumSummaryCollection : oci.DataOciMulticloudExternalLocationSummariesMetadata.IDataOciMulticloudExternalLocationSummariesMetadataExternalLocationSummariesMetadatumSummaryCollection
    {
    }
}
