using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementManagedDatabasesDatabaseParameters
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementManagedDatabasesDatabaseParameters.DataOciDatabaseManagementManagedDatabasesDatabaseParametersDatabaseParametersCollection")]
    public class DataOciDatabaseManagementManagedDatabasesDatabaseParametersDatabaseParametersCollection : oci.DataOciDatabaseManagementManagedDatabasesDatabaseParameters.IDataOciDatabaseManagementManagedDatabasesDatabaseParametersDatabaseParametersCollection
    {
    }
}
