using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseAutonomousContainerDatabases
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseAutonomousContainerDatabases.DataOciDatabaseAutonomousContainerDatabasesAutonomousContainerDatabasesAssociatedBackupConfigurationDetails")]
    public class DataOciDatabaseAutonomousContainerDatabasesAutonomousContainerDatabasesAssociatedBackupConfigurationDetails : oci.DataOciDatabaseAutonomousContainerDatabases.IDataOciDatabaseAutonomousContainerDatabasesAutonomousContainerDatabasesAssociatedBackupConfigurationDetails
    {
    }
}
