using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementDbManagementPrivateEndpoints
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementDbManagementPrivateEndpoints.DataOciDatabaseManagementDbManagementPrivateEndpointsDbManagementPrivateEndpointCollectionItems")]
    public class DataOciDatabaseManagementDbManagementPrivateEndpointsDbManagementPrivateEndpointCollectionItems : oci.DataOciDatabaseManagementDbManagementPrivateEndpoints.IDataOciDatabaseManagementDbManagementPrivateEndpointsDbManagementPrivateEndpointCollectionItems
    {
    }
}
