using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciApmSyntheticsOnPremiseVantagePoints
{
    [JsiiByValue(fqn: "oci.dataOciApmSyntheticsOnPremiseVantagePoints.DataOciApmSyntheticsOnPremiseVantagePointsOnPremiseVantagePointCollectionItemsWorkersSummaryAvailableCapabilities")]
    public class DataOciApmSyntheticsOnPremiseVantagePointsOnPremiseVantagePointCollectionItemsWorkersSummaryAvailableCapabilities : oci.DataOciApmSyntheticsOnPremiseVantagePoints.IDataOciApmSyntheticsOnPremiseVantagePointsOnPremiseVantagePointCollectionItemsWorkersSummaryAvailableCapabilities
    {
    }
}
