using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseMigrationAssessmentAssessorChecks
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseMigrationAssessmentAssessorChecks.DataOciDatabaseMigrationAssessmentAssessorChecksAssessorCheckSummaryCollectionItemsCheckActionUserDefinedPropertiesPropertiesOptions")]
    public class DataOciDatabaseMigrationAssessmentAssessorChecksAssessorCheckSummaryCollectionItemsCheckActionUserDefinedPropertiesPropertiesOptions : oci.DataOciDatabaseMigrationAssessmentAssessorChecks.IDataOciDatabaseMigrationAssessmentAssessorChecksAssessorCheckSummaryCollectionItemsCheckActionUserDefinedPropertiesPropertiesOptions
    {
    }
}
