using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciOsManagementHubManagedInstanceGroupManagedInstances
{
    [JsiiByValue(fqn: "oci.dataOciOsManagementHubManagedInstanceGroupManagedInstances.DataOciOsManagementHubManagedInstanceGroupManagedInstancesManagedInstanceCollectionItemsLifecycleStage")]
    public class DataOciOsManagementHubManagedInstanceGroupManagedInstancesManagedInstanceCollectionItemsLifecycleStage : oci.DataOciOsManagementHubManagedInstanceGroupManagedInstances.IDataOciOsManagementHubManagedInstanceGroupManagedInstancesManagedInstanceCollectionItemsLifecycleStage
    {
    }
}
