using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDbmulticloudOracleDbAwsIdentityConnectors
{
    [JsiiByValue(fqn: "oci.dataOciDbmulticloudOracleDbAwsIdentityConnectors.DataOciDbmulticloudOracleDbAwsIdentityConnectorsOracleDbAwsIdentityConnectorSummaryCollectionItemsServiceRoleDetails")]
    public class DataOciDbmulticloudOracleDbAwsIdentityConnectorsOracleDbAwsIdentityConnectorSummaryCollectionItemsServiceRoleDetails : oci.DataOciDbmulticloudOracleDbAwsIdentityConnectors.IDataOciDbmulticloudOracleDbAwsIdentityConnectorsOracleDbAwsIdentityConnectorSummaryCollectionItemsServiceRoleDetails
    {
    }
}
