using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciLustreFileStorageLustreFileSystems
{
    [JsiiByValue(fqn: "oci.dataOciLustreFileStorageLustreFileSystems.DataOciLustreFileStorageLustreFileSystemsLustreFileSystemCollectionItemsMaintenanceWindowMetadataActiveOrNextPlannedMaintenance")]
    public class DataOciLustreFileStorageLustreFileSystemsLustreFileSystemCollectionItemsMaintenanceWindowMetadataActiveOrNextPlannedMaintenance : oci.DataOciLustreFileStorageLustreFileSystems.IDataOciLustreFileStorageLustreFileSystemsLustreFileSystemCollectionItemsMaintenanceWindowMetadataActiveOrNextPlannedMaintenance
    {
    }
}
