using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementManagedDatabaseUserDataAccessContainers
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementManagedDatabaseUserDataAccessContainers.DataOciDatabaseManagementManagedDatabaseUserDataAccessContainersDataAccessContainerCollection")]
    public class DataOciDatabaseManagementManagedDatabaseUserDataAccessContainersDataAccessContainerCollection : oci.DataOciDatabaseManagementManagedDatabaseUserDataAccessContainers.IDataOciDatabaseManagementManagedDatabaseUserDataAccessContainersDataAccessContainerCollection
    {
    }
}
