using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatascienceMlApplicationImplementations
{
    [JsiiByValue(fqn: "oci.dataOciDatascienceMlApplicationImplementations.DataOciDatascienceMlApplicationImplementationsMlApplicationImplementationCollectionItemsConfigurationSchema")]
    public class DataOciDatascienceMlApplicationImplementationsMlApplicationImplementationCollectionItemsConfigurationSchema : oci.DataOciDatascienceMlApplicationImplementations.IDataOciDatascienceMlApplicationImplementationsMlApplicationImplementationCollectionItemsConfigurationSchema
    {
    }
}
