using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDataSafeMaskingPolicyReferentialRelations
{
    [JsiiByValue(fqn: "oci.dataOciDataSafeMaskingPolicyReferentialRelations.DataOciDataSafeMaskingPolicyReferentialRelationsMaskingPolicyReferentialRelationCollectionItemsParent")]
    public class DataOciDataSafeMaskingPolicyReferentialRelationsMaskingPolicyReferentialRelationCollectionItemsParent : oci.DataOciDataSafeMaskingPolicyReferentialRelations.IDataOciDataSafeMaskingPolicyReferentialRelationsMaskingPolicyReferentialRelationCollectionItemsParent
    {
    }
}
