using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDataSafeSecurityAssessmentTemplateAssociationAnalytics
{
    [JsiiByValue(fqn: "oci.dataOciDataSafeSecurityAssessmentTemplateAssociationAnalytics.DataOciDataSafeSecurityAssessmentTemplateAssociationAnalyticsTemplateAssociationAnalyticsCollectionItems")]
    public class DataOciDataSafeSecurityAssessmentTemplateAssociationAnalyticsTemplateAssociationAnalyticsCollectionItems : oci.DataOciDataSafeSecurityAssessmentTemplateAssociationAnalytics.IDataOciDataSafeSecurityAssessmentTemplateAssociationAnalyticsTemplateAssociationAnalyticsCollectionItems
    {
    }
}
