using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseAutonomousDatabaseBackups
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseAutonomousDatabaseBackups.DataOciDatabaseAutonomousDatabaseBackupsAutonomousDatabaseBackupsSourceDatabaseDetailsAutonomousDatabaseCustomerContacts")]
    public class DataOciDatabaseAutonomousDatabaseBackupsAutonomousDatabaseBackupsSourceDatabaseDetailsAutonomousDatabaseCustomerContacts : oci.DataOciDatabaseAutonomousDatabaseBackups.IDataOciDatabaseAutonomousDatabaseBackupsAutonomousDatabaseBackupsSourceDatabaseDetailsAutonomousDatabaseCustomerContacts
    {
    }
}
