using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciTenantmanagercontrolplaneSubscriptionAvailableRegions
{
    [JsiiByValue(fqn: "oci.dataOciTenantmanagercontrolplaneSubscriptionAvailableRegions.DataOciTenantmanagercontrolplaneSubscriptionAvailableRegionsAvailableRegionCollectionItems")]
    public class DataOciTenantmanagercontrolplaneSubscriptionAvailableRegionsAvailableRegionCollectionItems : oci.DataOciTenantmanagercontrolplaneSubscriptionAvailableRegions.IDataOciTenantmanagercontrolplaneSubscriptionAvailableRegionsAvailableRegionCollectionItems
    {
    }
}
