using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciBdsBdsInstanceBdsCapacityReservationConfigurations
{
    [JsiiByValue(fqn: "oci.dataOciBdsBdsInstanceBdsCapacityReservationConfigurations.DataOciBdsBdsInstanceBdsCapacityReservationConfigurationsBdsCapacityReservationConfigurationCollectionItems")]
    public class DataOciBdsBdsInstanceBdsCapacityReservationConfigurationsBdsCapacityReservationConfigurationCollectionItems : oci.DataOciBdsBdsInstanceBdsCapacityReservationConfigurations.IDataOciBdsBdsInstanceBdsCapacityReservationConfigurationsBdsCapacityReservationConfigurationCollectionItems
    {
    }
}
