using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseManagementManagedDatabaseAttentionLogCounts
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseManagementManagedDatabaseAttentionLogCounts.DataOciDatabaseManagementManagedDatabaseAttentionLogCountsAttentionLogCountsCollectionItems")]
    public class DataOciDatabaseManagementManagedDatabaseAttentionLogCountsAttentionLogCountsCollectionItems : oci.DataOciDatabaseManagementManagedDatabaseAttentionLogCounts.IDataOciDatabaseManagementManagedDatabaseAttentionLogCountsAttentionLogCountsCollectionItems
    {
    }
}
