using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciCertificatesManagementCertificateAuthorityVersions
{
    [JsiiByValue(fqn: "oci.dataOciCertificatesManagementCertificateAuthorityVersions.DataOciCertificatesManagementCertificateAuthorityVersionsCertificateAuthorityVersionCollectionItemsValidity")]
    public class DataOciCertificatesManagementCertificateAuthorityVersionsCertificateAuthorityVersionCollectionItemsValidity : oci.DataOciCertificatesManagementCertificateAuthorityVersions.IDataOciCertificatesManagementCertificateAuthorityVersionsCertificateAuthorityVersionCollectionItemsValidity
    {
    }
}
