using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciOsManagementHubSoftwareSourceAvailableSoftwarePackages
{
    [JsiiByValue(fqn: "oci.dataOciOsManagementHubSoftwareSourceAvailableSoftwarePackages.DataOciOsManagementHubSoftwareSourceAvailableSoftwarePackagesSoftwarePackageCollection")]
    public class DataOciOsManagementHubSoftwareSourceAvailableSoftwarePackagesSoftwarePackageCollection : oci.DataOciOsManagementHubSoftwareSourceAvailableSoftwarePackages.IDataOciOsManagementHubSoftwareSourceAvailableSoftwarePackagesSoftwarePackageCollection
    {
    }
}
