using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciJmsFleetUncorrelatedPackageManagedInstances
{
    [JsiiByValue(fqn: "oci.dataOciJmsFleetUncorrelatedPackageManagedInstances.DataOciJmsFleetUncorrelatedPackageManagedInstancesUncorrelatedPackageManagedInstanceUsageCollectionItems")]
    public class DataOciJmsFleetUncorrelatedPackageManagedInstancesUncorrelatedPackageManagedInstanceUsageCollectionItems : oci.DataOciJmsFleetUncorrelatedPackageManagedInstances.IDataOciJmsFleetUncorrelatedPackageManagedInstancesUncorrelatedPackageManagedInstanceUsageCollectionItems
    {
    }
}
