using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciOpensearchOpensearchClusterPipelines
{
    [JsiiByValue(fqn: "oci.dataOciOpensearchOpensearchClusterPipelines.DataOciOpensearchOpensearchClusterPipelinesOpensearchClusterPipelineCollectionItemsReverseConnectionEndpoints")]
    public class DataOciOpensearchOpensearchClusterPipelinesOpensearchClusterPipelineCollectionItemsReverseConnectionEndpoints : oci.DataOciOpensearchOpensearchClusterPipelines.IDataOciOpensearchOpensearchClusterPipelinesOpensearchClusterPipelineCollectionItemsReverseConnectionEndpoints
    {
    }
}
