using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatascienceMlApplicationInstances
{
    [JsiiByValue(fqn: "oci.dataOciDatascienceMlApplicationInstances.DataOciDatascienceMlApplicationInstancesMlApplicationInstanceCollectionItemsPredictionEndpointDetailsPredictionUris")]
    public class DataOciDatascienceMlApplicationInstancesMlApplicationInstanceCollectionItemsPredictionEndpointDetailsPredictionUris : oci.DataOciDatascienceMlApplicationInstances.IDataOciDatascienceMlApplicationInstancesMlApplicationInstanceCollectionItemsPredictionEndpointDetailsPredictionUris
    {
    }
}
