using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatascienceComputeTarget
{
    [JsiiByValue(fqn: "oci.dataOciDatascienceComputeTarget.DataOciDatascienceComputeTargetComputeConfigurationDetailsScalingPolicyAutoScalingPoliciesRulesScaleOutConfiguration")]
    public class DataOciDatascienceComputeTargetComputeConfigurationDetailsScalingPolicyAutoScalingPoliciesRulesScaleOutConfiguration : oci.DataOciDatascienceComputeTarget.IDataOciDatascienceComputeTargetComputeConfigurationDetailsScalingPolicyAutoScalingPoliciesRulesScaleOutConfiguration
    {
    }
}
