using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DatabaseCloudExadataInfrastructureConfigureExascaleManagement
{
    [JsiiByValue(fqn: "oci.databaseCloudExadataInfrastructureConfigureExascaleManagement.DatabaseCloudExadataInfrastructureConfigureExascaleManagementMaintenanceWindowDaysOfWeek")]
    public class DatabaseCloudExadataInfrastructureConfigureExascaleManagementMaintenanceWindowDaysOfWeek : oci.DatabaseCloudExadataInfrastructureConfigureExascaleManagement.IDatabaseCloudExadataInfrastructureConfigureExascaleManagementMaintenanceWindowDaysOfWeek
    {
    }
}
