using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseAutonomousContainerDatabaseBackupListAutonomousDatabasesInBackups
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseAutonomousContainerDatabaseBackupListAutonomousDatabasesInBackups.DataOciDatabaseAutonomousContainerDatabaseBackupListAutonomousDatabasesInBackupsAutonomousDatabaseInBackupCollection")]
    public class DataOciDatabaseAutonomousContainerDatabaseBackupListAutonomousDatabasesInBackupsAutonomousDatabaseInBackupCollection : oci.DataOciDatabaseAutonomousContainerDatabaseBackupListAutonomousDatabasesInBackups.IDataOciDatabaseAutonomousContainerDatabaseBackupListAutonomousDatabasesInBackupsAutonomousDatabaseInBackupCollection
    {
    }
}
