using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciMulticloudExternalLocationMappingMetadata
{
    [JsiiByValue(fqn: "oci.dataOciMulticloudExternalLocationMappingMetadata.DataOciMulticloudExternalLocationMappingMetadataExternalLocationMappingMetadatumSummaryCollectionItems")]
    public class DataOciMulticloudExternalLocationMappingMetadataExternalLocationMappingMetadatumSummaryCollectionItems : oci.DataOciMulticloudExternalLocationMappingMetadata.IDataOciMulticloudExternalLocationMappingMetadataExternalLocationMappingMetadatumSummaryCollectionItems
    {
    }
}
