using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseToolsDatabaseToolsMcpToolsetVersions
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseToolsDatabaseToolsMcpToolsetVersions.DataOciDatabaseToolsDatabaseToolsMcpToolsetVersionsDatabaseToolsMcpToolsetVersionCollectionItemsVersionsTools")]
    public class DataOciDatabaseToolsDatabaseToolsMcpToolsetVersionsDatabaseToolsMcpToolsetVersionCollectionItemsVersionsTools : oci.DataOciDatabaseToolsDatabaseToolsMcpToolsetVersions.IDataOciDatabaseToolsDatabaseToolsMcpToolsetVersionsDatabaseToolsMcpToolsetVersionCollectionItemsVersionsTools
    {
    }
}
