using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDbmulticloudOracleDbGcpIdentityConnectors
{
    [JsiiByValue(fqn: "oci.dataOciDbmulticloudOracleDbGcpIdentityConnectors.DataOciDbmulticloudOracleDbGcpIdentityConnectorsOracleDbGcpIdentityConnectorSummaryCollectionItemsGcpNodes")]
    public class DataOciDbmulticloudOracleDbGcpIdentityConnectorsOracleDbGcpIdentityConnectorSummaryCollectionItemsGcpNodes : oci.DataOciDbmulticloudOracleDbGcpIdentityConnectors.IDataOciDbmulticloudOracleDbGcpIdentityConnectorsOracleDbGcpIdentityConnectorSummaryCollectionItemsGcpNodes
    {
    }
}
