using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciFleetAppsManagementRunbookVersions
{
    [JsiiByValue(fqn: "oci.dataOciFleetAppsManagementRunbookVersions.DataOciFleetAppsManagementRunbookVersionsRunbookVersionCollectionItemsTasksTaskRecordDetailsExecutionDetailsVariablesInputVariables")]
    public class DataOciFleetAppsManagementRunbookVersionsRunbookVersionCollectionItemsTasksTaskRecordDetailsExecutionDetailsVariablesInputVariables : oci.DataOciFleetAppsManagementRunbookVersions.IDataOciFleetAppsManagementRunbookVersionsRunbookVersionCollectionItemsTasksTaskRecordDetailsExecutionDetailsVariablesInputVariables
    {
    }
}
