using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciStackMonitoringMonitoredResourceTasks
{
    [JsiiByValue(fqn: "oci.dataOciStackMonitoringMonitoredResourceTasks.DataOciStackMonitoringMonitoredResourceTasksMonitoredResourceTasksCollectionItemsTaskDetailsResourceTypesConfigurationHandlerConfigHandlerProperties")]
    public class DataOciStackMonitoringMonitoredResourceTasksMonitoredResourceTasksCollectionItemsTaskDetailsResourceTypesConfigurationHandlerConfigHandlerProperties : oci.DataOciStackMonitoringMonitoredResourceTasks.IDataOciStackMonitoringMonitoredResourceTasksMonitoredResourceTasksCollectionItemsTaskDetailsResourceTypesConfigurationHandlerConfigHandlerProperties
    {
    }
}
