using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciOsManagementHubManagedInstanceInstalledWindowsUpdates
{
    [JsiiByValue(fqn: "oci.dataOciOsManagementHubManagedInstanceInstalledWindowsUpdates.DataOciOsManagementHubManagedInstanceInstalledWindowsUpdatesInstalledWindowsUpdateCollection")]
    public class DataOciOsManagementHubManagedInstanceInstalledWindowsUpdatesInstalledWindowsUpdateCollection : oci.DataOciOsManagementHubManagedInstanceInstalledWindowsUpdates.IDataOciOsManagementHubManagedInstanceInstalledWindowsUpdatesInstalledWindowsUpdateCollection
    {
    }
}
