using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseMigrationAssessmentAssessors
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseMigrationAssessmentAssessors.DataOciDatabaseMigrationAssessmentAssessorsAssessorSummaryCollectionItemsAssessorGroupActionsUserDefinedPropertiesPropertiesOptions")]
    public class DataOciDatabaseMigrationAssessmentAssessorsAssessorSummaryCollectionItemsAssessorGroupActionsUserDefinedPropertiesPropertiesOptions : oci.DataOciDatabaseMigrationAssessmentAssessors.IDataOciDatabaseMigrationAssessmentAssessorsAssessorSummaryCollectionItemsAssessorGroupActionsUserDefinedPropertiesPropertiesOptions
    {
    }
}
