using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDatabaseMigrationAssessmentAssessors
{
    [JsiiByValue(fqn: "oci.dataOciDatabaseMigrationAssessmentAssessors.DataOciDatabaseMigrationAssessmentAssessorsAssessorSummaryCollectionItemsAssessorGroupActionsUserDefinedPropertiesProperties")]
    public class DataOciDatabaseMigrationAssessmentAssessorsAssessorSummaryCollectionItemsAssessorGroupActionsUserDefinedPropertiesProperties : oci.DataOciDatabaseMigrationAssessmentAssessors.IDataOciDatabaseMigrationAssessmentAssessorsAssessorSummaryCollectionItemsAssessorGroupActionsUserDefinedPropertiesProperties
    {
    }
}
