using Amazon.JSII.Runtime.Deputy;

#pragma warning disable CS0672,CS0809,CS1591

namespace oci.DataOciDbmulticloudOracleDbGcpKeyRings
{
    [JsiiByValue(fqn: "oci.dataOciDbmulticloudOracleDbGcpKeyRings.DataOciDbmulticloudOracleDbGcpKeyRingsOracleDbGcpKeyRingSummaryCollectionItemsReplicationMetadataReplicationDetails")]
    public class DataOciDbmulticloudOracleDbGcpKeyRingsOracleDbGcpKeyRingSummaryCollectionItemsReplicationMetadataReplicationDetails : oci.DataOciDbmulticloudOracleDbGcpKeyRings.IDataOciDbmulticloudOracleDbGcpKeyRingsOracleDbGcpKeyRingSummaryCollectionItemsReplicationMetadataReplicationDetails
    {
    }
}
